# ---
# # yaml-language-server: $schema=https://kochhaus-schemas.pages.dev/dragonflydb.io/dragonfly_v1alpha1.json
# apiVersion: dragonflydb.io/v1alpha1
# kind: Dragonfly
# metadata:
#   name: dragonfly
# spec:
#   image: ghcr.io/dragonflydb/dragonfly:v1.27.2
#   replicas: 3
#   env:
#     - name: MAX_MEMORY
#       valueFrom:
#         resourceFieldRef:
#           resource: limits.memory
#           divisor: 1Mi
#     - name: REDIS_PASSWORD
#       valueFrom:
#         secretKeyRef:
#           name: dragonfly-secret
#           key: REDIS_PASSWORD
#   args:
#     - --maxmemory=$(MAX_MEMORY)Mi
#     - --proactor_threads=2
#     - --cluster_mode=emulated
#     - --default_lua_flags=allow-undeclared-keys
#     - --lock_on_hashtags
#     - --requirepass=$(REDIS_PASSWORD)
#   resources:
#     requests:
#       cpu: 50m
#       memory: 256Mi
#     limits:
#       memory: 1Gi
#   topologySpreadConstraints:
#     - maxSkew: 1
#       topologyKey: "kubernetes.io/hostname"
#       whenUnsatisfiable: "DoNotSchedule"
#       labelSelector:
#         matchLabels:
#           app.kubernetes.io/part-of: dragonfly

---
# yaml-language-server: $schema=https://crd.movishell.pl/dragonflydb.io/dragonfly_v1alpha1.json
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: dragonfly
spec:
  labels:
    dragonflydb.io/cluster: dragonfly
  image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.27.2 #@sha256:e1bdd6ff1ed32efdfb5a07ddf954689a3d69791ae905a1f2197d8aa381ef8e7c
  replicas: 3
  nodeSelector:
    kubernetes.io/arch: arm64
  args:
    - --maxmemory=$(MAX_MEMORY)M
    - --default_lua_flags=allow-undeclared-keys #https://github.com/immich-app/immich/issues/2542
    - --proactor_threads=2
    - --cluster_mode=emulated
    - --lock_on_hashtags
    - --s3_endpoint=${SECRET_S3_ENDPOINT}
    # - --platform linux/amd64
    # - --requirepass=$(REDIS_PASSWORD)
  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor: 1M
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          key: AWS_ACCESS_KEY_ID
          name: dragonfly-secret
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          key: AWS_SECRET_ACCESS_KEY
          name: dragonfly-secret
  resources:
    requests:
      cpu: 100m
      memory: 128M
    limits:
      memory: 512M
  snapshot:
    dir: "s3://dragonfly"
  serviceSpec:
    type: LoadBalancer
    annotations:
      lbipam.cilium.io/ips: 10.0.10.5
      external-dns.alpha.kubernetes.io/hostname: redis.${SECRET_DOMAIN}
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: "kubernetes.io/hostname"
      whenUnsatisfiable: "DoNotSchedule"
      labelSelector:
        matchLabels:
          app.kubernetes.io/part-of: dragonfly
