---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name dragonfly-secret
spec:
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        AWS_ACCESS_KEY_ID: "{{ .MINIO_ACCESS_KEY }}"
        AWS_SECRET_ACCESS_KEY: "{{ .MINIO_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: dragonfly-tfm-minio
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
