---
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
type: Opaque
data:
  ADMIN_TOKEN: 2C0XWDAE3Ihv_7mQd_Q4HYAjIzfhfcLgIqvkaUOd
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: vaultwarden-db-secret
# type: Opaque
# data:
#   DATABASE_URL: <base64-encoded-database-url>
