apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
type: Opaque
data:
  ADMIN_TOKEN: ENC[AES256_GCM,data:tDC0q1DYQKXJ8xlFZ+rRiiSnVxY=,iv:IJRE+2ksyvbiBEirb3RJz805Rb9jkOMI9qKPDzYNBZw=,tag:4ewaHNsj+cnGFa4d+3zntQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMnU0UU5HSHFvQ2J2TDZP
        T1lGSHBwNldmWWFDZWR1NHYya3NMNXlNZUFrCjBYZEN5YkN1bjBHdEFJckRqd0Qy
        eHBFOS9WZGZVdEs4VmFnMlljaXcwekkKLS0tIFdMTXUxNnFPeVlNODdGSHRPUEJU
        N01DRG5qWXZGbHgyQXErYjhRK0dGdTAKyP2RUgoPmsXLcW6kLz2qMTdz/R3RBxDY
        qBlVrOnfB7jbbMLCNgRgiS76Ah4eJdEZc/GTT93Bf6QgpFBogksaJw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-02T17:57:52Z"
  mac: ENC[AES256_GCM,data:txXaIkBrnlmX2K5ztv++Df2U7GknowSykaEMYf0ZBbMyg9qwG1XRX/KPnYof2XDpvYfIGBr875a475i6MHMD2CxS7Y4JdJ9BpQsumWfag2IToB7Jmp0ik+xb2piWtkK0y2vN/kHM3RNjQmNFUOIUrb2mZ6lOVVwLUTXWEpJyUDE=,iv:/CVOR6RJWWfEE+BJNL/VUtTr+iV7cA+bmLVhANYzhw0=,tag:XV1q8NXgsZ2O95ZWmyl0lA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
