---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dragonfly
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: dragonfly-secret
    template:
      engineVersion: v2
      data:
        REDIS_PASSWORD: "{{ .DRAGONFLY_REDIS_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .MINIO_ACCESS_KEY }}"
        AWS_SECRET_ACCESS_KEY: "{{ .MINIO_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: dragonfly
    - extract:
        key: dragonfly-tfm-minio
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
