---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph-external
resources:
  - ./rook-ceph/ks.yaml
  # - ./namespace.yaml
components:
  - ../../flux/components/common
  # - ../../../shared/meta/components/alerts
  # - ../../../shared/meta/components/global-vars
  # - ../../../shared/meta/components/namespace
  # - ../../../shared/meta/components/sops
