# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:FVhf0HQuSrnXlXTcded4XRCyclAplNfOy90D/pzzOxkipsV1,iv:yppEkxwCPdC2mTXgsrBNo5UGwlCE9xKuVo6whqPn/l0=,tag:H8dD79uQYQpxPr29up0oKA==,type:str]
  credentials.json: ENC[AES256_GCM,data:TyTh3vBqlgBwpqCzhyeGSaHQ4X2b4LWF+b3Kv3y7w6yO6+71n4ipX/h7klvykjZwwddmEekjLx868fKJ9D491hZLRjqcw77BVMAt0jpjOg7quoZmUUaA17eeaXgNmpQKusnyZaU1B4IsZJZ4bI95b6ntaCkONhPGcfiqNVdMfuomwRsiGz0nYZtRD5v6MfngIHmKC514YweSSRTW45KXjTWAq+bNhhtF14xxtSID/Q==,iv:1m+ZAL1DaG8ARErKPJCVX9HFoBLqZueZ8DncaT3D5Go=,tag:y1zQise7Lj1FyWfUoIsVkw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbzJtV2tWUFh3Z2ZNL0dn
        K0JKZzVqeUphRmJjaVppSVZiaWcrcStiZW5nCjBNdFdNdnRMbGZDbko0Rlk2b1Bu
        SkJYQWlIeWFYampLN2xRanpqWlk2ZzQKLS0tIFpPZ0Rlc2hrZndPOSsvVWFNMDRL
        YjZvSmV6NVR2TjFWWTBhWnpHYWNWaDgKQquRcbUOGQXuszyJoEtH/7uzLvg2wYgy
        eTHwRVYLMUhlevRBHbAJ3l8G2/cI5aRIMoYZEAxrkOb0FJw9PwSToA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-25T18:32:44Z"
  mac: ENC[AES256_GCM,data:A+MS75oDeDr5gUzkNlvnomB1CCl4y6GNTx/zddSgVB8FM+J4+XWVCDnyQPFAQi1TnctXXy7PC52JlFeKpwuEceChSIBMVgfN8K18vA7uJYIMBmNViLXOJ8/NfCi1GHhhWj0neaL/0I14U6IQQQYsLknwCFkndNw1VUzdIPz2xrA=,iv:MpLlgwcxSr1yPH5Mp5N7de+d5aBBq3XF4EmiYMdnW3U=,tag:Gj8cvFnQ/zzIhRI4C2RzXg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
