# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:AtOZtWnfXXf7cZlxTcKRGItKZtpTIaWjltSwNA58tVE62hID,iv:PiumSPXMgWxoW/7QGEzW9XD0faetIySuH+XgANz8mJk=,tag:bxKkqUvqklniuSV+aTdobQ==,type:str]
  credentials.json: ENC[AES256_GCM,data:t+O5SH4ffiJy9IabHlCYpwqbpgzzBkjxUqNp03FOgBwueO+fYrjnRVFJ4yLK4CKV0ChLFsQo/or85oXo5Dai/wzULpXk6H0lzdXRJLu1v0eCUjVHNgAShNi6jo8RnTdCRLte3IDj2czma5IZfAFiXtfjfxlebuIUHgrjQl9/v+gNMdeRtGKrjYpQLl58Ho18Bn4A/ciChQdq8CvA/EJ7MM43leaDiOcfuleieOGs2w==,iv:ObskgkffZi/7T0EEOEmvd/CW0Cz/ugI1WzYfljdnPms=,tag:i7FCpSl9Ta+xX5Em6E38Dg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdm9sVVFoU3pVMWJIOWMv
        MHg5Z1RPYkpscm54MFRIYWtUZTVqWEF3Vms4CkpxdjBUVG4vbFFqUFAzeGxnbjJN
        MEw5MG0zU0VURlBIR3R4czh1OFlRaDAKLS0tIHp1OUhaMllJdFVYTko2aXdxUitG
        RThCYU8zOXBYSWdUeWc0QTV2WmVnNVEKzr8aRXLkET4DRN/vi10FdS6zoaVs0Jo5
        IAFctWAUGHb3kEjJQheuqFyztJAvyeySAayOdxyH70Ph21DRGriyIA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-25T22:00:48Z"
  mac: ENC[AES256_GCM,data:ylf/mbC7vl5hX4u4yksgfvt2lOM/srnEiSw5LS5zPUGfpDZxOtB5VgSg5RYXK32psjrtPnMnDZ+vhEJbcEIhK+c4nKVlMIa6RmKDDHXmFknyG2YBXE+rYO32prsUN/814SO5kS8DpMUgoejGcVDFmwP9wfXXlfVXxWIA0EnhyrA=,iv:2N0jqyCOSV0Ssth55k3LonZoh2fzuyJZQMRayZvsVUU=,tag:+OvBBH6mFQs/b6egANhcNA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
