---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app minio
  # namespace: storage
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    defaultPodOptions:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: *app
              topologyKey: "kubernetes.io/hostname"
    controllers:
      minio:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 1
        # pod:
        #   securityContext:
        #     runAsUser: 568
        #     runAsGroup: 568
        #     fsGroup: 568
        #     fsGroupChangePolicy: "OnRootMismatch"
        #     supplementalGroups:
        #       - 100
        #       - 65539
        containers:
          main:
            image:
              repository: quay.io/minio/minio
              tag: RELEASE.2025-01-20T14-49-07Z
            env:
              TZ: "Africa/Johannesburg"
              MINIO_UPDATE: "off"
              MINIO_PROMETHEUS_URL: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
              MINIO_PROMETHEUS_JOB_ID: minio
              MINIO_PROMETHEUS_AUTH_TYPE: public
              MINIO_BROWSER_REDIRECT_URL: "https://minio.home.${SECRET_DOMAIN}"
              MINIO_SERVER_URL: "https://cdn.${SECRET_DOMAIN}"
            envFrom:
              - secretRef:
                  name: minio-secret
            args: ["server", "/data", "--console-address", ":9001"]
            resources:
              requests:
                memory: 100Mi
                cpu: 100m
              limits:
                memory: 2Gi
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /minio/health/live
                    port: &api-port 9000
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 6
              readiness: *probes

    service:
      minio:
        controller: minio
        ports:
          http:
            port: &console-port 9001
          api:
            enabled: true
            port: *api-port

    # https://min.io/docs/minio/linux/reference/minio-mc-admin/mc-admin-prometheus.html
    serviceMonitor:
      main:
        serviceName: minio
        endpoints:
          - port: api
            scheme: http
            path: /minio/v2/metrics/cluster
            interval: 1m
            scrapeTimeout: 10s
            # bearerTokenSecret:
            #   name: minio-secret
            #   key: MINIO_PROMETHEUS_TOKEN

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          #   hajimari.io/enable: "true"
          #   hajimari.io/appName: "Minio Console"
          #   hajimari.io/group: "storage"
          #   hajimari.io/icon: mdi:pail
          #   hajimari.io/instance: "admin"
          #   gethomepage.dev/enabled: "true"
          #   gethomepage.dev/description: S3 storage
          #   gethomepage.dev/group: Storage
          #   gethomepage.dev/icon: sh-minio.svg
          #   gethomepage.dev/name: Minio
          #   gethomepage.dev/app: minio
          external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
        hosts:
          - host: minio.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
      s3:
        enabled: true
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
          # hajimari.io/enable: "false"
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
          nginx.ingress.kubernetes.io/proxy-body-size: 1024m
          nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            chunked_transfer_encoding off;
        hosts:
          - host: s3.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: api

    persistence:
      config:
        type: nfs
        server: "192.168.86.200"
        path: "/mnt/datastore/k3sdata/minio"
        globalMounts:
          - path: /data
