apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  # Change to your namespace
  namespace: storage
type: Opaque
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:1XurAfrea3RBEA==,iv:CU1eESDnEgeolnGIdEbm0zovMvdSyZzkP9B8zw+7gEg=,tag:BHoYgXHVdvKKrEwTlGO2Iw==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:FaNX7PBMWMJl2laM,iv:g6KJYAQjuHDY7K96CK1VuPEP14KVquST6IOq0lBV7s4=,tag:2u2ca4Bk/lleygfo+JU8KA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYd0l1aHVJZkxkRFhTeWhI
        NC9IbXQxWUVRNXpmWjhRUkp3UjJZRE5pNERvClJuN0plQ3p1bFlaa3E2dGFnWkFU
        WG9mOVQwUWFMSDluemJIWDM0bTh1L2MKLS0tIEJldW8zTzNBTXM2R2Zkc3RELzJU
        MERTZ2ZyZG16NFJYd0t3VVE4V3RMbTgKh65drS+Pcdr23yQRp57PU7BemJvBfwX0
        1qUqNIr7kn1mODC+WaBPEig+VHbqDdrM1sguLXiS2dFc1cmIDEFmYw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-01T21:26:25Z"
  mac: ENC[AES256_GCM,data:DBswHioB3vbzn44bBp9mirGUUDjVPASIQW/bNhi38p89LgmpLjUpcmKf5PpD0JbFPm7qsEWdG6hHUyJrHqL6nkvE2hIVY56NkohnAMbaMdb69mmlwBC97S6qB3ZSltYCGnN4oHCF+Qe7ehjdS+67kb5nawI6Ufq6Fx2ndsk/E50=,iv:X0/DVZDOtDRMIOwbpru2gaQ3JG5cW91JGH9H/mn3kbo=,tag:cI0NfnqlBl1TcyrKb6kRuw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
