apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  # Change to your namespace
  namespace: storage
type: Opaque
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:B1RZl6pOQL5gKw==,iv:2+K4mG3FPLXvjgr84SVm7Adc9dl9+PMAT775ygxtGfk=,tag:4Z27Xsa1eiUzyUzpEPA5tQ==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:u8JW6LhCcxdoTDeg,iv:Zh0RYSPH59dGkYVtbpUXhqYCAB4eizt2yfay6pB7onY=,tag:QOyT/ZhfI/hJRwzg5PCJLA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCakFPSWFSTDZBWVJSVHdW
        emdGZDZWQk9PVDVtU2RHMjRCQklPSFZ3R1JjCnc2MndVSU5za0NYQUNycFFPSFIx
        anVLazdQeTdKZFJvdXg5Y2plSVlkNGsKLS0tIEsrWG92aXoyc0UvMEpNZGM2N3NU
        Z1BQZXBPS2dQN1VwdWVKVjlva3VrQVEKhAR4bcV4T4+GfFnWU1D/bTyuY0pp/Jr4
        GmxLjeoykJ4PdxD5lgZFcXRd0fJV3oeQKmUcUMh1rJjt0NDHW1pSow==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-27T11:12:08Z"
  mac: ENC[AES256_GCM,data:UbzGmmHY14tQ3HuhCrSBVA54erQcBtsWJuuNnABPD26+mnJB3ebMbEBsVFSwtLiByi4Iva8Sx9ofq/jd5M9NNbcB0TKkyzrpd6/R6IapMTPLADuIRVKEEzUYInk8uIYqKWxpuIh8lKmzwxwbMMOCWG8rzJiDXzMiBgEGkcJhKuA=,iv:frAyTFt7HgibwFZ7PSubES4ERPeM1+VNszPpVIHech4=,tag:JrP6ueszJeAM+uo8Igw3iQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
