apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  # Change to your namespace
  namespace: storage
type: Opaque
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:LZLskULSIcZf5A==,iv:ufYoZSuAaPYU5gIaWTBuK/LrUAqnhJVAInlMLqxZjIQ=,tag:KUAX3uGC1nCI+qLs8W5PpA==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:ke9Dh7t2vBqsYqLR,iv:ysngeJU7ucl/RR6kP1/6z/5e4VVqfoGXl/zndqeUB7c=,tag:iLqh+wFWMgllUVsALRaxxQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0blErTDF6NWM0bnFlQzhw
        dVpkU0ptTno2UmRPZmRmb2huMy9EOEFUSXljCmREbHEwN1Y4M1VFWGFQZkh4bVdk
        bm9MOXJxdVFWS3o3VlErZFVrb3VjVjQKLS0tIC9Zc1c4SXhSZXE4Z0MwTHNBNkww
        Wk5VUjN4b1BsczdlZ1g4SFpJOHM1elUKOpIWtprKht6Pd8asjEvOY0vV/05hkpPK
        ftCrVJb3HpWg7Ohz3/tI1nMirvBh09tXhqre00JiZ3tKS2idQMwnHw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-27T10:56:31Z"
  mac: ENC[AES256_GCM,data:x8UHwgJfESmEtSOHcTvxbDWhPiyV9P7OqZvcy8UM8J+93W05NeeWOG+OPLjSPvYsA075UrUnHDnaanKPFNi9gGneAYvM/ly/W91ce224lNhhnY4B0R3Vwfble0yJAncP8kOKJXDC1P5Y1JDv7NYM2pv/T+/ev9Ztq125IwExk8c=,iv:BZrtPywOu0rdge+8vEX5nUVo6GsxZkJJK1053kZcD9M=,tag:VScLRZRqSCGkoPx1mZyYLg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
