apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  # Change to your namespace
  namespace: storage
type: Opaque
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:VV7/ClyFY18/aw==,iv:5PET0PY7zLoL2g7yVNZr/qUQafMYDWNjwufhccFlHVE=,tag:vIegX6mRiMRIrjENJ3gkhA==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:Tv9yCFRXRbyDvWr6,iv:/W5U8vCRg+lvBTBGAG288uhKCgmHFOQY3KGkfXVptro=,tag:E0IAf5VcSHuV2n91IFqDww==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZDlndGh2RWlyajVsaDVB
        M2tFQWhpUHJaOVh0S0o1VGEyRmU2YXZUOGtFCkVXdEw5NVlGZTJveHIvbVRKTVMx
        bEZYQjB1VnR6U2xWNDZaRXgzQU9uOWMKLS0tIDNWVlExNHNPWGxUT2VPVEJ6cUlN
        OHgrbk9ab3cra2M3T3NKSzdKNmNjT2cK/lnYtdCGHxpwlc/IyXOvHXQmS1XQ/TsU
        IeCcpWPq0PfgqYEqV9NhQyHSukwxyblUgLzEFBk6gEpuBrPGlwGyAA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-02T13:17:18Z"
  mac: ENC[AES256_GCM,data:cNlsjLpfUQQZNpu3dTNKgJCYimlJpqo7tncUurQZA9fq/LW18Zx4CEskqeIJ3ac/8lTsjkcvQjvPAB0JIT7dza/+Gw9BbuBU6AuwR+85w92nfQmJhJxl5/nDDJJEXanyixwCf/vwPZTZZ4uuHJDll0WVE86CBYVchlb4mGvz4QM=,iv:LwbzPW67dQ0YcO27TZmP89EaRCYlNAtO7ljMHLVmA4I=,tag:H+JI3SMD5KkXfDYVYQO4bQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
