# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:pdJoLykytkK4V7ExIgwwGYlyT1ArWr7vy7POkJz0SGg=,iv:ceW5VL7mlTSwW7oSL12FIbby8xxhhlRHppbODre6PcM=,tag:5MH5BouPbKpDYWOQCRzk2Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dXk5bktyYkFnakZOTGp6
        bGJ1elUzVVlWQy9QUWQwM0NUbUMrMUVVZWxFClJDTVFQV2txU2RRY3JKUCswNkZK
        Ums5VEQrSUl2Z1JqM2MwTkxCNDlWTncKLS0tIDRuVm5IbHVDbkp3Sjc2YXRDVjdy
        Y2tVaFdKU2dzUDZXNTNDMGgzem9GQ0UKcQqGzG6P5aTIjFiWy+nq8nYg8V8zHvyw
        xVpyCMxiallKw3G0IAt7mZlruiTa9YG0/fIuQyi9Sqc/wygi8M/LMA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-25T20:09:06Z"
  mac: ENC[AES256_GCM,data:9yAOMhsf7IRTRQ5PWaBCi3XFwbkSxHrP+njp7iDhQV1nIkII8iz82aRvXOaEV4eapTJbKn2CT8FtVv9eUIY9ga4yhgNHa7JzFN+eK1cjFI3FPAoBChZtlQhIEhl3XPlSGnprItQU19QJ0NDR5WEu3sV6lYsRmR7aGcr129b7FCs=,iv:0Jgm/bXpId0LrjnHEkEwLlvX1VBMFK/+E12pkloR9Ds=,tag:kkkJO2U3km3QngPuYTLBwQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
