# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:y3+KPHOH+oaxn+EBL7yJKghH0nIGGHOH25dn2f5tBfs=,iv:01pba2bsLaK/bLHsCZmZZ95np+04YFLvC0+Ei0IEJek=,tag:Mz8lYlkMcpONftz1xKYIjQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQlRacHBUNGhYRnFuU2g2
        R28xTTd4UnFuaXlmUnVLL0d1cFhyRFlmRDFFCjVLU2RSZXc2eEFqZDVMQ29ta2o1
        STJIL2J6bk5IN1g5QTZXUXphWEtXam8KLS0tIDdLQ3pFakh3SklySGpzd0MyTU0r
        RjRiK0tQRkhZWUNwaERQa3d1ZzZTSHcK/JiqMTx87vUA4qPl1GU4DzjCg0DWHk2p
        Ttnj8kHuN80W/nZWuvTHNjJcGgZGcsBv8/mohqbXVi6Gyxs8w7HC4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-25T19:35:22Z"
  mac: ENC[AES256_GCM,data:+w/syL+zvZF06h1pROJMAvJDYneMRWH9nf3zZFqaLFsBS7ZseiUV4Sm/ColqoLScsUCJIPvjQFtsbpBN7oJJGAX6dtH+4a5HVvbo6oOtPy7/QKoqOF1KFOLMnGXnds682NvIhqgLB+Ln7sjVGflp/E1Gwnd6ld6dGd+19SN+8Os=,iv:q6wZlotnWKFTrFj5caPQzvu/oKid7Ti5Lf5g97bxK2w=,tag:utOWYql+KVKxrJlgTL2sTg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
