# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:fWASLVi1j/eNmlNLWdQ8771QXdSz/qbDI6CeqGGatfA=,iv:qbKDvNSFwrQpx1zGUoe5hJaBQ79DRENJcYdXXj2n9Cc=,tag:a6OuCYugnP8CKefOiWrmsw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTWJsYmdwVVhNTmJvUVQ1
        RXVYOUQ2c3lXeHVpa2R3SG8wT09OMHhya3hJCjlvbE5SUU5RTzJySXpoQXcyb3Ay
        QmdnUlhCNkRqTldxN0Fla2xFUDJ6Y1EKLS0tIGtETS9HZng4djg4bS9RUUVKMzVQ
        UTVWa3ltdzJtQ2FhNms3bDhEY0ZqU1UKZ8GbjTkyvuwOODGUzLIXbzxZeSO7YCO7
        /KFLMaU4R6rEflilh4Z/gOQ0VrouTxQRhbVnyOmclCTgwfuSCCPAQg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-25T18:52:31Z"
  mac: ENC[AES256_GCM,data:yb0CSfLfus6JB0LzIxEJRwa4L7iQXMF/IePQMOpW+RhcqYvbknjPU2+08tiDN+WmreEyQ7YKsKKzLFUOIfAbIctZv8gW58DP9bE0IdC3KRnX/gc1jaAQvTH8eIjCietUG1oqnCi4xeT/kmOz6vz7FioGOTdSOKVzDA9B7lvm/r0=,iv:PdGw1+k+OxG+TodYg+upHUuAcBZpjVz8SRKzSfnsLuM=,tag:zGApTig8jI191ZvnvCrQ3w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
