# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:ZI7FnEBHpEgNzPz//h0nZIjEn4rQKDuYit25dLJI7vA=,iv:WRWbTXaDm737779aOP3RGw85IkEQnH2P3uJ2wWGicww=,tag:qIXeB2q+0XGEkH+bVEVK1g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZzByU2tzbk5rdFBnL3B2
        Yk1zMnQ4WGVXTHdFWkU3SFJ2Zk9IWVlDd2xzCmh2NENydnQ0K2NrS2wzeTlFeEV5
        OGhVc25BUEJQTWw3c3BtRUYxdFhDM00KLS0tIHg0TG1lZHhsY2ZnVERVOHZ2YTJq
        ekVxdjlLWVBSNkN5VDM5S3Yzb1J0b0EKY9F288i2ygeq1jwVC6w/O+qDxI10FGuw
        W6PF9AxZqoBZjbFjDUcfGlsNP6I3qLMs3qJRTanJaHi/QL2QrxqxVQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-25T22:00:48Z"
  mac: ENC[AES256_GCM,data:0Y2kMu8rKdDPcgcUS9rYWwBoahYxIF68hTtiCo7cIL0VNciD+tbG1Vo58iLJVQQiTRZtD2ciddNZz5CObyUgZ/MfsDFpuaz4axIzKuELgIQulpvuGXhAuZ+IYBoG8OOcwRf9bJsiWvZHQFUZdVM/AP7PrKhWJnLl2OHmWjZJANk=,iv:V8X2I9UlzgUmo4Q8gow8b3GiDFhw806RSqD0UMGzUEY=,tag:VJWTi0ha1Um6O1J8ePb4EQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
