# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:9qa55LVc1cBYZuBDzdeBg7jxvrOjTjizAbFLoh/xTJU=,iv:ppqvjFtI8NFlWRXdJYIromZ32OR7ruPoUOVdXS0kqkc=,tag:60dJmHYz0w3UxXMnO+TXvQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNVB3R1ZjZE8zUG5wK0Zu
        akNRYmlHVEdxT0dyU2NlYXlnRjR1Ny95RGdRCmd3VnRhV2RaZ3lCTlR3UzdIZEJq
        UmJCU3ZvMXlMUm02RSsvM253aHY0OU0KLS0tIEdzenU5Nkt4VDBGMUZ6NVdrS3FO
        UUFQUHdLY3RDVmM1QVFtY2IvVzVIM00KWqgf/EcsuiOz7xPCV/EyfImjlQbZkPHK
        fIXCmlA6y3B8YfoM/4wd71AXIlXg2Qqr/rNV2NV4eBxaqR5QhQIW8Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-25T18:32:44Z"
  mac: ENC[AES256_GCM,data:cwyV4aMYi0yI7FA6AgeoSduFdfXmtdNYm8ggC4Qpd3X+sA7aHWHHV+wDcKdBmovRTUMEIad5HbsaT/nM5+kgTTTPhZYSPY4yeCsXeH4BIK4CAG0o25OoP4uVQXDyI0ULD0RyXkXo9kkZHI5bkbM0MALSxO6qv0gZDk+KIXMSqOI=,iv:T+v/XXmgsPN6dGsMzbgKv2TCg01nKzkZ4B0tc5Ibv5c=,tag:sawaGYcug91kxIXwyVWpWg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
