# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Si2hLWBoj8VmTBSxP7wD8ITmzrrK4i4fJCnuzfEp7Jc=,iv:Cde2xfFmM0fc5WT+OdOoL1w4stP4yY9Jv98bONiH6uM=,tag:W3WZbgzQ4juUUlJQ4WRliw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcUQ4WjdZTWxtbkZwTHdC
        L3E3YVdnSHd4TnNSTDU2cjZyelNiZ0RqSEhvCi8rMVBlanhJci93MExrampFYjJQ
        dXdYSDR3MHBxZWdzL0JBSXVLZTF6TlUKLS0tIGo2ZmlES0ZPcjhZTkJRNGN1RnB3
        S3V2M1h0RUMwakxMTjJ5M0pUTnRFVlEKV7ZXulXhS6VFEAtQ9VZqgFxjDIFgCXcT
        g6QdR9m262g9ZDHUVEmultYNp0jUarGPA12I7nzNsN2emS0Vc8Lwrg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-25T18:40:26Z"
  mac: ENC[AES256_GCM,data:WRAa5tw8v5bOyziyxfpc6qo7KH1KGQlOkUpL2PAy7ihDrUvxHduPBak63Btn9PDWuRqhzAV7pUjnfmQLpgyLkIlRwexOqeBeOCt5Ll9IUDsYK9vEDMSZQz4rYyyjYj7P1jPGOqcYb113kYgaqiRqVN2uEJYJ+qIcbGaTFwkAGl4=,iv:nWOXho/IwMppTfvPqgMDmfKVlpJ9BZwRvHAI4wsYMdE=,tag:nvPqEd5MmxjpOkqIr5laUw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
