# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &app vaultwarden
#   namespace: flux-system
# spec:
#   targetNamespace: vaultwarden
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: *app
#   path: ./kubernetes/apps/default/vaultwarden/app
#   components:
#     - ../../../components/volsync
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   # targetNamespace: vaultwarden
#   dependsOn:
#     # - name: crunchy-postgres-operator-cluster
#     # - name: external-secrets-stores
#     - name: rook-ceph-cluster
#     - name: volsync
#   wait: false
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m
#   postBuild:
#     substitute:
#       APP: *app
#       VOLSYNC_CAPACITY: 2Gi
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app vaultwarden
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/vaultwarden/app
  components:
    - ../../../components/volsync
    - ../../../components/gatus/external
  postBuild:
    substitute:
      APP: *app
      # VOLSYNC_CLAIM: portainer-pvc
      VOLSYNC_CAPACITY: 2Gi
      # VOLSYNC_START_MINUTE: "11"
      VOLSYNC_CACHE_CAPACITY: "1Gi"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: vaultwarden
  dependsOn:
    - name: crunchy-postgres-operator-cluster
      namespace: database
    # - name: onepassword
    #   namespace: external-secrets
    # - name: haproxy
    #   namespace: rook-ceph-external
    # - name: volsync
    #   namespace: storage
