# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: descheduler
# spec:
#   interval: 30m
#   chart:
#     spec:
#       chart: descheduler
#       version: 0.32.2
#       sourceRef:
#         kind: HelmRepository
#         name: descheduler
#         namespace: flux-system
#   install:
#     remediation:
#       retries: 3
#   upgrade:
#     cleanupOnFail: true
#     remediation:
#       strategy: rollback
#       retries: 3
#   values:
#     replicas: 1
#     kind: Deployment
#     deschedulerPolicyAPIVersion: descheduler/v1alpha2
#     deschedulerPolicy:
#       profiles:
#         - name: Default
#           pluginConfig:
#             - name: DefaultEvictor
#               args:
#                 evictFailedBarePods: true
#                 evictLocalStoragePods: true
#                 evictSystemCriticalPods: true
#                 nodeFit: true
#             - name: RemovePodsViolatingInterPodAntiAffinity
#             - name: RemovePodsViolatingNodeAffinity
#               args:
#                 nodeAffinityType:
#                   - requiredDuringSchedulingIgnoredDuringExecution
#             - name: RemovePodsViolatingNodeTaints
#             - name: RemovePodsViolatingTopologySpreadConstraint
#               args:
#                 constraints:
#                   - DoNotSchedule
#                   - ScheduleAnyway
#           plugins:
#             balance:
#               enabled:
#                 - RemovePodsViolatingTopologySpreadConstraint
#             deschedule:
#               enabled:
#                 - RemovePodsViolatingInterPodAntiAffinity
#                 - RemovePodsViolatingNodeAffinity
#                 - RemovePodsViolatingNodeTaints
#     service:
#       enabled: true
#     serviceMonitor:
#       enabled: true
#     leaderElection:
#       enabled: true

---
# yaml-language-server: $schema=https://crd.movishell.pl/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler
spec:
  chart:
    spec:
      chart: descheduler
      version: 0.32.2
      sourceRef:
        kind: HelmRepository
        name: descheduler
        namespace: flux-system
  interval: 30m
  maxHistory: 3
  uninstall:
    keepHistory: false
  values:
    kind: Deployment
    schedule: "*/5 * * * *"
    deschedulerPolicy:
      profiles:
        - name: Default
          pluginConfig:
            - name: DefaultEvictor
              args:
                evictFailedBarePods: true
                evictLocalStoragePods: true
                evictSystemCriticalPods: true
                nodeFit: true
            - name: RemovePodsViolatingInterPodAntiAffinity
            - name: RemovePodsViolatingNodeAffinity
              args:
                nodeAffinityType:
                  - requiredDuringSchedulingIgnoredDuringExecution
            - name: RemovePodsViolatingNodeTaints
            - name: RemovePodsViolatingTopologySpreadConstraint
              args:
                constraints:
                  - DoNotSchedule
                  - ScheduleAnyway
            - name: LowNodeUtilization
              args:
                thresholds:
                  cpu: 20
                  memory: 20
                  pods: 20
                targetThresholds:
                  cpu: 50
                  memory: 50
                  pods: 50
            - name: RemoveFailedPods
              args:
                reasons:
                  - NodeShutdown
                  - ImagePullBackOff
                  - CreateContainerConfigError
                exitCodes:
                  - 1
                includingInitContainers: true
                excludeOwnerKinds:
                  - Job
                minPodLifetimeSeconds: 3600
            - name: RemovePodsHavingTooManyRestarts
              args:
                podRestartThreshold: 5
                includingInitContainers: true
          plugins:
            balance:
              enabled:
                - LowNodeUtilization
                - RemovePodsViolatingTopologySpreadConstraint
            deschedule:
              enabled:
                - RemovePodsHavingTooManyRestarts
                - RemovePodsViolatingInterPodAntiAffinity
                - RemovePodsViolatingNodeAffinity
                - RemovePodsViolatingNodeTaints
                - RemoveFailedPods
    service:
      enabled: true
    serviceMonitor:
      enabled: true
    leaderElection:
      enabled: true