---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app crunchy-postgres-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: pgo
      version: 5.7.4
      sourceRef:
        kind: HelmRepository
        name: crunchydata
        namespace: flux-system
  maxHistory: 2
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    monitoring: true
    install:
      clusterLabels:
        app.kubernetes.io/name: pgo
    replicas: 2
    # topologySpreadConstraints:
    #   - maxSkew: 1
    #     topologyKey: "topology.kubernetes.io/zone"
    #     whenUnsatisfiable: "ScheduleAnyway" #"DoNotSchedule"
    #     labelSelector:
    #       matchLabels:
    #         postgres-operator.crunchydata.com/control-plane: pgo
