# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:T1UN+8x/RTUF7AbiUUfajQicOuHhD59Bwd9wgauY0hFK2VsIDh+5iQ==,iv:Bq+OhhFXkndfFIQlvouMs5+QA8ctCTmBEPqkbtEHVZQ=,tag:nnFtWrZd+Ovr7Z3DC3afGw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxejk3eDcvdVJadXl4Y0pM
        TlFLelZ1MmtOUVVyQnB4bWYyYkVrK2dLNEh3CjdhVHcwTnV3NUpTNXFQUTBlcThF
        L3pieGZGZXpGWmh4Q0pNVi9MY3ptRTAKLS0tIHFWWkZvTWU3eUVaSG00elI0ZWcv
        TDljcTRQY210Y01xZVFQdDE4V3hwMTQK1usUJQMCrVu49m7kHc72XfGPKgA7x8aB
        KXrdf3MMJJgY4YENfKQg1xLkJ/6L7vUKignLT5EAh65amGKd8U5HvA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-25T18:32:44Z"
  mac: ENC[AES256_GCM,data:hRC0BGM18Gh84MnS1MREVV7H7t4Q1WX3FsiArS357/+RBdCbCmgr+fBLyrnelEgfN2jbknCjBZgKM2ZLT53ObHMM6d6UeYF1+27CZPNy4C9+fRNjJDfdECeuZ7SIgNMrBMTGz4mVStgbE3POrqUSQLqxhE3XHNyunT1p3pQ+adw=,iv:p9SbS6sFVGJakd7799aVcazccUePD3z66+LkMEKzIoU=,tag:QGk1HOec9QujqdjWYd9BhA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
