# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:VdEbrgD08M3yhjSBIKXCjPHCDOshn/e+p9gsaj7e5+YZCSO7fkwBSA==,iv:hipvCiOo4CZmmUL9b9klbdHdHgyQLvBRctHaDkccMRw=,tag:+MrMjbGVm4fovAd86sN1Sg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4c0VWOEVBeUEyME1VOUNW
        elNXb1pPdllwYng4WG54L0cxNWYxaDlFemxFCmZ5OHYwdHN0bVJ3Z1JSMURjczNJ
        RnVxKy9ZUHI2cjh5NmJGd255WjVneDAKLS0tIERBUnJNdDFJcnlDRmxIenBESWpk
        Umo0WlRWZHF0S0UwUUpTNVlvUGtwUGcKv51kVfXHqoUEHmWOLYdyQe9QLTiSNRUg
        yoWPpkp9lPBANGjc/snu3WtHwYmIF2B4XtLhNmgZDFBpEMN05wFLVw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-25T18:40:26Z"
  mac: ENC[AES256_GCM,data:jGSRQZlxQP1s6KJtmlPce6w+udJqTY5IgQO9sekzq+l82qIY0qX9uVCfjwLuih+N1D63H5f0KbUnuY8GgYrKAB9oo0E+rJ6h6UABZLyqbHfHbrCEYOXpecwCKpxuyk9Qyqc/J83HT4OULIder19q1+3IIqeW223ThtJ8y/l01d8=,iv:JQn+Vv3BPnoJEpQXHf1fxhBgOClUQG8czjT+42l5vWg=,tag:inu/9RHaiAhKBT2YG3Ralg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
