# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:UfVIJ06VqA27jdtmf4pY6JEw0KnDbUj5HF1Vptmanr/bpej9y15Dmw==,iv:q9zuKftWckR2rekkI2FuAk8UOitItotR1huwDEdPdeU=,tag:8pOZl6Zz4cVljasHDtPzwA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SUlhZW9mTXhPdzJpNm80
        ZUFkdDVpYUxEblEyOXJpRVV3M0pBOXhXNjBJCmpoUkVhOEhvclEvRVZZd0dGUit6
        TktXaVhSbG02REFXbzI3anc5WjkzZU0KLS0tIFRXZ3BGemExTFMvMU1EVXB5NE11
        Z0NiZFc1VXh6TVhZaks5VGM5VExoSTQKkTdJOICo8ZKe84+GQWwBQZj+bjeYOi6T
        HabngAWVARYGaDy/ffzw6NOt+Xn6AkUOQRAB5GBR4BBwd3LmTOV+6g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-25T18:52:31Z"
  mac: ENC[AES256_GCM,data:E/js25+fm21JAm5/PkwlNmrUwg4SrzBapNbVvA8fMrwOYw+1wTkiLb8fkaT7Yu0ytHIya0eiLIt9paa8pcQwVo70IUvXWau9VN3Y6kiqkeYIHneWM9b8gOEt9H8P+qxLsViojkiNlYZDsQgBpJBzUmMRUCcvd17RCmf9AyB3Ovg=,iv:xeL/AHTRYkz0GTqrzs4aBP94X5EBJTxb/wXo4wuOoOU=,tag:4mQDPJTkrc1A65pGaj11WA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
