# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:06VbhZTJ5ZopBf4Q1KJyWq3YcM1UGLmPfdCZekbw+z5JGZ3Zc4cRhQ==,iv:SokyBaRFjPgnUXFEYsFFryDwFbO1uoinSinYJLva0jk=,tag:nKym3e5nc+LwBtB8kHOLcg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCOEwzL1d4THJURnNYMWlr
        MVJjYVhOSEtnSllQTWNzcWtJL3lsUUFkSTA4Cm1mM3dEenJmemN0NWZLREFnNTRr
        OHF1eVNXczloczM1ZTRneXlmSG53MWMKLS0tIFNFNG9Mam9IWmV3Z29NZm5PQk0w
        MFB0ZHJnc25sdnhaaG9zSXppaHRweW8KXldt0B1hSBP+2dC+h6vb9RNLHVWPL+h1
        dQKlwvuTmiSUhmUIp1U6HD8AzJ0kmROrOagjnUgi5pJdtKb7Ga0K4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-25T20:09:06Z"
  mac: ENC[AES256_GCM,data:ywUTNTVURColnaE/8EXRcB2F6IXbZCowKRP0Z34xkgTUMlQ1I6kC8xebXzMAZ8e9WDxRtuvg5tIMGvy/puVOLBxPiYInOaHAScwAVVq682Zgv7BVMvmH/UHFsKcbbegwT8n46RR720FgueZn1V6FkWEf0Wxmmrwb0iFZnQBnxSQ=,iv:DjFI1wF47qLjYRBaXj9CfRanokJA2GhmgUW2bZOfNd8=,tag:Bpeyi+l8FH05xGNZMuklwQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
