# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:qy8l22Tb2t1AJyqxYA+HH6i6T8K7bzPgRQqsBRht9HGj24awfYti4A==,iv:rOXfKp0l07/YTVFjp1XBq1DK5spGKsur5815X04ZVio=,tag:ZmZ/WKfvdXkO9AYX4hpkJA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpR3JIc2g0K0pLM3RaSlow
        ZjVpa296akZCcU84R3pWdU9aL2d2K2RWYXhRCml1RndNZllJMVQvL0Z2aC9TT0xC
        YXNrRVZrYVhwZUpwOWM2R1lxVDB4TmMKLS0tIGJ5NmdxRVdsVGxHeDc2eU1ZNWlN
        TDRMMmJvcTlUV0NjUGpnZFkvYW16MXMK3ZBklaZ7GL/1KrV8FbfRV8CG4T06iLV4
        k0FZJFiBtNm0atsUtyKzyBmDO0nQe3fjWHWd43/eyRCXmoUfkwHTrg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-25T19:35:22Z"
  mac: ENC[AES256_GCM,data:zblNePUvXJpnJ3qKzzNo5u9Kyar4lt778ylL6G+4Akz54KzlSMZ3veDfNwqDME+Lc/l8zUym1RY/3rQQS3MLmfM/YbzeWBd/QOPGonoht5BAOasPhwIpuJvL6b3qWNYpcD5hhElm+ZRfiZW+FPGQ+uNjQpDolPM1lHBi6E5U+KY=,iv:J/epCwHUA/dgLVhH3OmCRR5hPxBhH8JHGtrIb9F0gvk=,tag:BpCcfYXC/pHAhCm/tkAngA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
