# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:9C2hZX7RO6iNFQTZIB0vdbrrWsxDNOulf+3eNNo//BYmMdd2cvmwvA==,iv:NtxxzB/RgyNb5UelMs+vMhdNj3aMPKhY4lI3rfIPUOU=,tag:uPrp8YIHmC6aFmLZX4VG7g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQXhHUGZXeUt6Rk9HSlhT
        cXVhVmhtdEpkQ3dlemxiRjVvaW1mSmRYWDFFCk5qck5EdC94aEJwWnRyY1VQOE1m
        b0c1OVF3ZWwwSFJwVmVCUi9zYWFtWnMKLS0tIGt4Y1VRZUU4TXdaY0RZSDFjcmdk
        MHZrY2hqZG1ubTRvRjlIeWZGTlV0YTQKTzQ814JTAfvt98xf2JReAkBNPE0l3pbm
        sYzfPcY5ODGsfI0LqZXw1pEjKGIJPGLOYyEltSc+2Z4QW+/fBIGGnQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-25T22:00:48Z"
  mac: ENC[AES256_GCM,data:q/asiK97ZbstVo6aW3OwKxFkM0WyzVn0lAGUmu35tliGgXG61mZA7vHcL828rHCP1mvjb2SkoSV+1nhxolk2ZpzdXO4+3CnApzJ4dWeJlC0A1wtGxBHMSOzXwkJgOxsiS4PYu5z4jGgoxxNj7tqRByv3zWql2crK63WadtCsm4Q=,iv:x9I/uG4gT9TqODGuMZ8lVxwGVkOePa75y02Om1Jz0g4=,tag:s+LpB6ykluJ2qMeaaZPD/A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
