---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name crunchy-postgres-vector
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: crunchy-postgres-vector-secret
    template:
      data:
        CLOUDFLARE_ACCOUNT_ID: "{{ .CF_ACCOUNT_ID }}"
        s3.conf: |
          [global]
          repo2-s3-key={{ .CF_R2_CPGO_VECTOR_ACCESS_KEY }}
          repo2-s3-key-secret={{ .CF_R2_CPGO_VECTOR_SECRET_KEY }}
          repo3-s3-key={{ .MINIO_ACCESS_KEY }}
          repo3-s3-key-secret={{ .MINIO_SECRET_KEY }}
        encryption.conf: |
          [global]
          repo1-cipher-pass={{ .CRUNCHY_PGO_CIPHER_PASS }}
          repo2-cipher-pass={{ .CRUNCHY_PGO_CIPHER_PASS }}
          repo3-cipher-pass={{ .CRUNCHY_PGO_CIPHER_PASS }}
  dataFrom:
    - extract:
        key: cloudflare
    - extract:
        key: crunchy-pgo
    - extract:
        key: crunchy-pgo-vector-tfm-minio
