---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name crunchy-pgo-vector-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        s3.conf: |
          [global]
          repo2-s3-key={{ .R2_ACCESS_KEY_ID }}
          repo2-s3-key-secret={{ .R2_SECRET_ACCESS_KEY }}
          repo3-s3-key={{ .MINIO_ACCESS_KEY }}
          repo3-s3-key-secret={{ .MINIO_SECRET_KEY }}
        encryption.conf: |
          [global]
          repo1-cipher-pass={{ .CRUNCHY_PGO_CIPHER_PASS }}
          repo2-cipher-pass={{ .CRUNCHY_PGO_CIPHER_PASS }}
          repo3-cipher-pass={{ .CRUNCHY_PGO_CIPHER_PASS }}
          repo4-cipher-pass={{ .CRUNCHY_PGO_CIPHER_PASS }}
  dataFrom:
    - extract:
        key: cloudflare
    - extract:
        key: crunchy-postgres
    - extract:
        key: minio
