---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-vector-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: postgres-vector
        group: infrastructure
        url: tcp://postgres-vector-primary.database.svc.cluster.local:5432
        interval: 1m
        conditions: ["[CONNECTED] == true"]
        alerts: [{ type: discord }]
        ui:
          hide-url: true
          hide-hostname: true
