---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: searxng
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: searxng-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        SEARXNG_SECRET: "{{ .SEARXNG_SECRET }}"
  dataFrom:
    - extract:
        key: SEARXNG
