apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 5m
  chart:
    spec:
      chart: rancher
      # version: 2.10.2
      sourceRef:
        kind: HelmRepository
        name: rancher-latest
        namespace: flux-system
  values:
    replicas: 1
    hostname: ranchertalos.${SECRET_DOMAIN}
    bootstrapPassword: "${SECRET_RANCHER_ADMIN_PASSWORD}"
