---
apiVersion: batch/v1
kind: Job
metadata:
  name: "unlock-${app}-${ts}"
  namespace: "${ns}"
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      automountServiceAccountToken: false
      restartPolicy: OnFailure
      containers:
        - name: unlock
          image: docker.io/restic/restic:latest
          args: ["unlock", "--remove-all"]
          envFrom:
            - secretRef:
                name: "${app}-volsync-${dest}"
          volumeMounts:
            - name: repository
              mountPath: /repository
      volumes:
        - name: repository
          nfs:
            server: 192.168.86.200
            path: /mnt/datastore/kubebackup/volsync
