---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app netboot
  namespace: &namespace utilities
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../flux/components/gatus/internal
    # - ../../../../flux/components/volsync
  #dependsOn:
  #- name: rook-ceph-cluster
  path: ./kubernetes/apps/utilities/netboot/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: *app
      # VOLSYNC_CAPACITY: 2Gi
      # VOLSYNC_ACCESSMODES: ReadWriteMany
      # VOLSYNC_STORAGECLASS: ceph-filesystem
      # VOLSYNC_SNAPSHOTCLASS: csi-ceph-filesystem
