---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud
spec:
  refreshInterval: 5m
  target:
    name: nextcloud-secret
    creationPolicy: Owner
    template:
      data:
        # Nextcloud
        ADMIN_USER: "{{ .NXC_ADMIN_USER }}"
        ADMIN_PASS: "{{ .NXC_ADMIN_PASS }}"
        METRICS_TOKEN: "{{ .NXC_METRICS_TOKEN }}"
        # db
        POSTGRES_HOST: &dbhost '{{ index . "host" }}:{{ index . "port" }}'
        POSTGRES_DB: &dbname '{{ index . "dbname" }}'
        POSTGRES_USER: &dbuser '{{ index . "user" }}'
        POSTGRES_PASSWORD: &dbpass '{{ index . "password" }}'
        # redis
        REDIS_HOST: "{{ .DF_HOST }}"
        REDIS_PORT: "{{ .DF_REDIS_PORT }}"
        REDIS_DB: "{{ .DF_REDIS_NXC_DB }}"
        # minio
        S3_BUCKET: "{{ .MINIO_BUCKET }}"
        S3_ACCESS_KEY: "{{ .MINIO_ACCESS_KEY }}"
        S3_SECRET_KEY: "{{ .MINIO_SECRET_KEY }}"
        # email
        SMTP_HOST: "{{ .EXTERNAL_SMTP_HOST }}"
        SMTP_USERNAME: "{{ .EXTERNAL_SMTP_USER }}"
        SMTP_PASSWORD: "{{ .EXTERNAL_SMTP_PASS }}"
        # oidc
        OIDC_CLIENT_ID: "{{ .NXC_AK_CLIENT_ID }}"
        OIDC_CLIENT_PASSWORD: "{{ .NXC_AK_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: dragonfly
      sourceRef: &onepassword
        storeRef:
          kind: ClusterSecretStore
          name: onepassword
    - extract:
        key: nextcloud
      sourceRef: *onepassword
    - extract:
        key: nextcloud-tfm-minio
      sourceRef: *onepassword
    - extract:
        key: external-smtp
      sourceRef: *onepassword
    - extract:
        key: crunchy-postgres-pguser-nextcloud
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-postgres
# ---
# # yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1beta1.json
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: nextcloud-db
# spec:
#   refreshInterval: 5m
#   target:
#     name: nextcloud-db-secret
#     creationPolicy: Owner
#     template:
#       data:
#         postgresql.crt: "{{ .pgbouncer-frontend.crt }}"
#   dataFrom:
#     - extract:
#         key: crunchy-postgres-pgbouncer
#       sourceRef:
#         storeRef:
#           kind: ClusterSecretStore
#           name: crunchy-postgres
