---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name nextcloud-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        # Nextcloud
        ADMIN_USER: "{{ .ADMIN_USER }}"
        ADMIN_PASS: "{{ .ADMIN_PASS }}"
        # POSTGRES_HOST: &dbhost postgres-16-rw.database.svc.cluster.local
        # POSTGRES_DB: &dbname nextcloud
        # POSTGRES_USER: &dbuser "{{ .POSTGRES_USER }}"
        # POSTGRES_PASSWORD: &dbpass "{{ .POSTGRES_PASS }}"
        # S3_ACCESS_KEY: "{{ .S3_ACCESS_KEY }}"
        # S3_SECRET_KEY: "{{ .S3_SECRET_KEY }}"
        S3_ACCESS_KEY: "{{ .MINIO_ACCESS_KEY }}"
        S3_SECRET_KEY: "{{ .MINIO_SECRET_KEY }}"
        # SMTP_HOST: "{{ .SMTP_HOST }}"
        # SMTP_USERNAME: "{{ .SMTP_USERNAME }}"
        # SMTP_PASSWORD: "{{ .SMTP_PASS }}"
        # METRICS_TOKEN: "{{ .METRICS_TOKEN }}"
        # OIDC_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        # OIDC_CLIENT_PASSWORD: "{{ .OIDC_CLIENT_SECRET }}"
        # Postgres Init
        # INIT_POSTGRES_DBNAME: ${POSTGRES_DB}
        # INIT_POSTGRES_HOST: ${POSTGRES_HOST}
        # INIT_POSTGRES_USER: ${POSTGRES_USER}
        # INIT_POSTGRES_PASS: ${POSTGRES_PASSWORD}
        # INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: nextcloud
    - extract:
        key: minio
    # - extract:
    #     key: smtp

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-db
spec:
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: nextcloud-db-secret
    template:
      type: Opaque
      data:
        # POSTGRES_USER: '{{ index . "user" }}'
        # POSTGRES_PASSWORD: '{{ index . "password" }}'
        POSTGRES_DB: '{{ index . "dbname" }}'
        POSTGRES_HOST: '{{ index . "host" }}'
        POSTGRES_USER: '{{ index . "user" }}'
        POSTGRES_PASSWORD: '{{ index . "password" }}'
        INIT_POSTGRES_DBNAME: '{{ index . "dbname" }}'
        INIT_POSTGRES_HOST: '{{ index . "host" }}'
        INIT_POSTGRES_USER: '{{ index . "user" }}'
        INIT_POSTGRES_PASS: '{{ index . "password" }}'
        INIT_POSTGRES_SUPER_PASS: '{{ index . "password" }}'
  dataFrom:
    - extract:
        key: postgres-16-pguser-nc
    # - extract:
    #     key: postgres-16-pguser-postgres
