# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: nextcloud-nfs
# spec:
#   capacity:
#     storage: 1Mi
#   accessModes:
#     - ReadWriteMany
#   storageClassName: nfs-slow
#   persistentVolumeReclaimPolicy: Retain
#   nfs:
#     server: "${NAS_IP}"
#     path: /mnt/datastore/k3sdata/nextcloud
#   mountOptions:
#     ["nfsvers=4.2", "nconnect=8", "hard", "noatime"]
#     # - nfsvers=4.2
#     # - nconnect=8
#     # - hard
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: nextcloud-nfs
# spec:
#   accessModes: ["ReadWriteMany"]
#   storageClassName: nextcloud-nfs
#   resources:
#     requests:
#       storage: 1Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-nfs
spec:
  storageClassName: nextcloud-nfs
  capacity:
    storage: 1Mi
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_IP}
    path: /mnt/datastore/k3sdata/nextcloud
  # Note: The first two options are strictly for NFSv4.2
  mountOptions: ["nfsvers=4.2", "nconnect=8", "hard", "noatime"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-nfs
  namespace: storage
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: nextcloud-nfs
  resources:
    requests:
      storage: 1Mi
