---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-nfs
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Mi
  nfs:
    path: "/mnt/datastore/kubebackup/postgres-cluster"
    server: ${NAS_IP}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-nfs
