---
# yaml-language-server: $schema=https://crd.movishell.pl/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: dragonfly-operator
      version: v1.1.9
      sourceRef:
        kind: HelmRepository
        name: dragonfly
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  uninstall:
    keepHistory: false
  maxHistory: 3
  values:
    serviceMonitor:
      enabled: false
    grafanaDashboard:
      enabled: true
      folder: storage
      annotations:
        name: grafana_folder
      labels:
        name: grafana_dashboard
