# ---
# # yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: unpoller
# spec:
#   refreshInterval: 5m
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: onepassword
#   target:
#     name: unpoller-secret
#     creationPolicy: Owner
#   data:
#     - secretKey: unifipoller_password
#       remoteRef:
#         key: Unifi Controller
#         property: unifipoller-token

---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name unpoller-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        UP_UNIFI_DEFAULT_API_KEY: "{{ .UNPOLLER_KEY }}"
  dataFrom:
    - extract:
        key: unifi
