# ---
# # yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: unpoller
# spec:
#   interval: 30m
#   chart:
#     spec:
#       chart: app-template
#       version: 3.7.3
#       interval: 30m
#       sourceRef:
#         kind: HelmRepository
#         name: bjw-s
#         namespace: flux-system

#   values:
#     controllers:
#       unpoller:
#         annotations:
#           reloader.stakater.com/auto: "true"

#         pod:
#           securityContext:
#             runAsUser: 2000
#             runAsGroup: 2000
#             fsGroup: 2000
#             fsGroupChangePolicy: "OnRootMismatch"

#         containers:
#           unpoller:
#             image:
#               repository: ghcr.io/unpoller/unpoller
#               tag: v2.14.1
#             env:
#               UP_UNIFI_DEFAULT_ROLE: home-ops
#               UP_UNIFI_DEFAULT_URL: https://192.168.86.1
#               UP_UNIFI_DEFAULT_VERIFY_SSL: false
#               # UP_UNIFI_DEFAULT_USER: lenox
#               UP_UNIFI_DEFAULT_PASS:
#                 valueFrom:
#                   secretKeyRef:
#                     name: unpoller-secret
#                     key: unifipoller_password
#               UP_INFLUXDB_DISABLE: true
#             probes:
#               liveness:
#                 enabled: true
#               readiness:
#                 enabled: true
#               startup:
#                 enabled: true
#                 spec:
#                   failureThreshold: 30
#                   periodSeconds: 5
#             resources:
#               requests:
#                 cpu: 10m
#                 memory: 100Mi
#               limits:
#                 memory: 500Mi

#     service:
#       app:
#         controller: unpoller
#         ports:
#           http:
#             port: 9130

#     serviceMonitor:
#       app:
#         serviceName: unpoller
#         endpoints:
#           - port: http
#             scheme: http
#             path: /metrics
#             interval: 2m # Unifi API only polls at 2m intervals
#             scrapeTimeout: 5s

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unpoller
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  values:
    controllers:
      unpoller:
        containers:
          app:
            image:
              repository: ghcr.io/unpoller/unpoller
              tag: v2.14.1@sha256:9ba73b1793ef332ae9b4b719ef0fc09f231d6276bc7b721cbb47961ed7792961
            env:
              TZ: ${TIMEZONE}
              UP_UNIFI_DEFAULT_ROLE: home-ops
              UP_UNIFI_DEFAULT_URL: https://192.168.86.1
              UP_PROMETHEUS_HTTP_LISTEN: 0.0.0.0:80
              UP_LOKI_DISABLE: false
              UP_LOKI_URL: http://loki-gateway.monitoring.svc.cluster.local
              UP_UNIFI_DEFAULT_SAVE_ALARMS: true
              UP_UNIFI_DEFAULT_SAVE_ANOMALIES: true
              UP_UNIFI_DEFAULT_SAVE_DPI: true
              UP_UNIFI_DEFAULT_SAVE_EVENTS: true
              UP_UNIFI_DEFAULT_SAVE_IDS: true
              UP_UNIFI_DEFAULT_SAVE_SITES: true
              UP_INFLUXDB_DISABLE: true
            envFrom:
              - secretRef:
                  name: unpoller-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: unpoller
        ports:
          http:
            port: 80
    serviceMonitor:
      app:
        serviceName: unpoller
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 2m # Unifi API only polls at 2m intervals
            scrapeTimeout: 10s
