---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/postgres-operator.crunchydata.com/postgrescluster_v1beta1.json
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: &name crunchy-postgres-vector
  labels:
    crunchy-userinit.ramblurr.github.com/enabled: "true"
    crunchy-userinit.ramblurr.github.com/superuser: &superuser "postgres"
spec:
  image: ghcr.io/benwalio/cdpgvecto.rs:ubi8-16.6-2-v0.3.0@sha256:5357f1251f76590bc036d1375f82ee5a7f0702336505d62d7408162018e7b4f6
  postgresVersion: 16
  monitoring:
    pgmonitor:
      exporter:
        resources:
          requests:
            cpu: 10m
            memory: 64M
          limits:
            memory: 512M

  patroni: # turn on sync writes to at least 1 other replica
    dynamicConfiguration:
      synchronous_mode: true
      postgresql:
        synchronous_commit: "on"
        parameters:
          max_connections: 500
          shared_preload_libraries: "vectors.so"
          search_path: '"$user", public, vectors"'
        pg_hba:
          - hostnossl all all 10.69.0.0/16 md5
          - hostssl all all all md5

  instances:
    - name: crunchy-postgres-vector
      metadata:
        labels:
          app.kubernetes.io/name: crunchy-postgres-vector
      replicas: &replicas 1
      dataVolumeClaimSpec:
        storageClassName: openebs-hostpath
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
      walVolumeClaimSpec:
        storageClassName: openebs-hostpath
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: "DoNotSchedule"
          labelSelector:
            matchLabels:
              postgres-operator.crunchydata.com/cluster: *name
              postgres-operator.crunchydata.com/data: crunchy-postgres-vector
  users:
    # Superuser
    - name: *superuser
      databases: ["postgres"]
      options: "SUPERUSER"
      password:
        type: AlphaNumeric
    # Applications
    - name: "immich"
      databases: ["immich"]
      options: "SUPERUSER"
      password:
        type: AlphaNumeric

  backups:
    pgbackrest:
      configuration: &backupConfig
        - secret:
            name: crunchy-postgres-vector-secret
      global: &backupFlag # Global
        compress-type: "lz4"
        compress-level: "9"
        archive-push-queue-max: 8GiB
        # PVC
        repo1-retention-full: "30" # days
        repo1-retention-full-type: "time"
        # R2
        repo2-block: "y"
        repo2-bundle: "y"
        repo2-path: /crunchy-pgo-vector
        repo2-retention-full: "7" # days
        repo2-retention-full-type: time
        repo2-s3-uri-style: path
        # # Minio
        repo3-block: "y"
        repo3-bundle: "y"
        repo3-path: /crunchy-pgo-vector
        repo3-retention-full: "30" # days
        repo3-retention-full-type: "time"
        repo3-s3-uri-style: path
      manual:
        repoName: repo1
        options:
          - --type=full
      metadata:
        labels:
          app.kubernetes.io/name: crunchy-postgres-vector-backup
      repos:
        - name: repo1
          volume: &nfs
            volumeClaimSpec:
              storageClassName: nfs-csi #csi-driver-nfs
              volumeName: crunchy-postgres-vector-nfs
              accessModes: ["ReadWriteMany"]
              resources:
                requests:
                  storage: 1Mi
          schedules:
            full: "30 1 * * 0" # Sunday at 01:30
            differential: "30 1 * * 1-6" # Mon-Sat at 01:30
            incremental: "30 3-23 * * *" # Every hour except 01:30-2:30
        - name: repo2
          s3: &r2
            bucket: db-backups
            endpoint: ${CPGO_R2_ENDPOINT}
            region: us-east-1 #https://developers.cloudflare.com/r2/api/s3/api/#bucket-region
          schedules:
            full: "30 2 * * 0" # Sunday at 02:30
            incremental: "30 2 * * 1-6/2" # Mon-Sat at 02:30, every 2nd day
        - name: repo3
          s3: &minio
            bucket: crunchy-vectors
            endpoint: s3.${SECRET_S3_ENDPOINT}
            region: us-east-1
          schedules:
            full: "15 1 * * 0" # Sunday at 01:15
            differential: "15 1 * * 1-6" # Mon-Sat at 01:15
            incremental: "15 3-23 * * *" # Every hour except 01:30-2:30
      jobs:
        ttlSecondsAfterFinished: 600

  # dataSource:
  #   pgbackrest:
  #     stanza: db
  #     configuration: *backupConfig
  #     global: *backupFlag
  #     repo:
  #       name: repo3
  #       # volume: *nfs
  #       s3: *minio

  proxy:
    pgBouncer:
      service:
        metadata:
          annotations:
            external-dns.alpha.kubernetes.io/hostname: cpgo-vector.${SECRET_DOMAIN}
            lbipam.cilium.io/ips: 10.0.10.7
        type: LoadBalancer
      port: 5432
      replicas: *replicas
      config:
        global:
          # Grafana requires session
          # Ref: https://github.com/grafana/grafana/issues/74260
          pool_mode: session
          client_tls_sslmode: prefer
          default_pool_size: "100"
          max_client_conn: "500"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              postgres-operator.crunchydata.com/cluster: *name
              postgres-operator.crunchydata.com/role: pgbouncer-vector
