apiVersion: v1
kind: Secret
metadata:
  name: crunchy-pgo-vector-secret
  namespace: database
type: Opaque
data:
  R2_ACCESS_KEY_ID: ENC[AES256_GCM,data:M1Xc3zv9EYBintAIUmANrUJwOF4wkSnSRL82q5zlFu0=,iv:gNpPUU7cbcNU6SJXUzIll1eC2LkwpLEgEnwnC2LeI8w=,tag:dEY7i8m6AMwfi7XOaPffbA==,type:str]
  R2_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:CjwGCtiRC/Qd3zojVQAXScppVAXM4ivrmYzmVC/VvlDek6AMM3A35sCUEVTyhbuUMCsT3UGqULML6iFbPfHrmA==,iv:gXj9FJ5F0sWo8QengO9xlOJm+Tt6/91B9Em2S1+EG5Y=,tag:OWTpdNHobr11FmNMfy/4EA==,type:str]
  MINIO_ACCESS_KEY: ENC[AES256_GCM,data:7CZGMqapl34MsWNT/hhvZwk3Y9Y=,iv:BS2qbdN/4Dfd+rLayvooMkvRtbHFeapmc1IJwsaPfHU=,tag:iDWG4bLrLn2RTlIXKRAL9w==,type:str]
  MINIO_SECRET_KEY: ENC[AES256_GCM,data:dMdm20EZmjYdajG2lYnVannRzhgS5GNDdYkvVZJWI6ZMh7PprDyJcw==,iv:QI/EiU4YVAkPLbqC01FteyZSSzxAzvJYMKeoVds/lSg=,tag:LOPGiqywycq1DWNvq8V0ig==,type:str]
  CRUNCHY_PGO_CIPHER_PASS: ENC[AES256_GCM,data:HSy6TmkPcmfCg1uUh7o=,iv:YZfVZlXTS732QZRWKvfqRbKLSopEEqtOlnN6is1CKXM=,tag:MgRf5gzqUQ+H1sm7FlMGDQ==,type:str]
  R2_ENDPOINT: ENC[AES256_GCM,data:mRR8ePLkP+Voq9WWIkRzf3zMRJL4OE9tTZ1HPYZ7pGFDxhawLVjSybnXi9V4sX7xUDVtsJ3xzFMF+SZDbrdxcd14HOvChCT04nJ6gg==,iv:JMbFM1yKIowrpCD5n8udR8m0PUwGgrzYAbVAyZxOA3M=,tag:PVunbs7tTD+FQpqZ8ks6BA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcTNUTGxIOVhEYytydURt
        YVNiaHJzZzdSY25TNldHZ083L25sOTJtZUVZCitQVTZsekl4ZjhhWDIyTHdDc3E0
        RnRGMU9tM3ZQMkp0UFhRL2VIRlE3MkkKLS0tIGZTMFZzZXZUVVFnYWVCN1ZnZnBi
        WXdRT1E3ZlAyaTVpNkVRMDlHajJlREUK6cT3z6Sa9jb0mzQ7/dEoUm3qtRqEUsXF
        1Q86Ar9tAwZctHDUqCVN49D0JO+KdevlPh5tOzpcw91nBeIcyVdx3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-03T21:16:41Z"
  mac: ENC[AES256_GCM,data:h5zPjYq3MOeIRg93YO/ROuzlV4LxMhxFxOjxe09uu+Go8NYadvc1XZfdkdbL6Xq4M3IoGcGr7773u2h5LacXAaXse7Inz1/5Y8tlwsnv9BPEbcNZpM8Ev11VMP0kcFzY66/gxxH+MqVjzKi/zPnW1MFWm/NHxRLv/x8NS5j6PsY=,iv:FqePeSd6psvrSQLaIveXvBk1dIwiT6FQ/z8dbbVUhBM=,tag:mnpRaVGoHACw4vC0VRPIjg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
