---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portainer
  namespace: flux-system
spec:
  interval: 6h
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph-external
  chart:
    spec:
      chart: portainer
      # version: 1.0.59
      sourceRef:
        kind: HelmRepository
        name: portainer
        namespace: flux-system
  values:
    persistence:
      enabled: true
      existingClaim: "portainer"
      size: 128Mi
      storageClass: ceph-rbd
    ingress:
      enabled: true
      ingressClassName: internal
      annotations:
        external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Container-Management
        gethomepage.dev/group: Tools
        gethomepage.dev/icon: portainer.svg
        gethomepage.dev/id: "{{ .Release.Name }}"
        gethomepage.dev/name: Portainer
      hosts:
        - host: &host "portainerl.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
