---
web:
  port: 8080
storage:
  type: sqlite
  path: /config/sqlite.db
  caching: true
metrics: true
debug: false
ui:
  title: Status | Gatus
  header: Status
# alerting:
#   pushover:
#     application-token: ${CUSTOM_PUSHOVER_APP_TOKEN}
#     user-key: ${CUSTOM_PUSHOVER_USER_KEY}
#     priority: 1
#     resolved-priority: 0
#     default-alert:
#       description: health-check failed
#       send-on-resolved: true
#       failure-threshold: 5
#       success-threshold: 3
connectivity:
  checker:
    target: 192.168.86.100:53
    interval: 1m
endpoints:
  - name: flux-webhook
    group: external
    url: https://flux-webhook.${SECRET_DOMAIN}
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 404"
    alerts:
      - type: pushover
  # - name: status
  #   group: external
  #   url: https://vaultwarden.hayani.xyz
  #   interval: 1m
  #   client:
  #     dns-resolver: tcp://1.1.1.1:53
  #     ignore-redirect: true
  #   conditions:
  #     - "[STATUS] == 200"
