---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app crunchy-postgres-operator
  namespace: &namespace database
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: csi-driver-nfs
      namespace: storage
  interval: 30m
  path: ./kubernetes/apps/database/crunchy-postgres/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app crunchy-postgres-cluster
  namespace: &namespace database
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  # dependsOn:
  #   - name: crunchy-postgres-operator
  #     namespace: *namespace
  #   - name: onepassword
  #     namespace: external-secrets
  healthCheckExprs:
    - apiVersion: postgres-operator.crunchydata.com/v1beta1
      kind: PostgresCluster
      failed: status.conditions.filter(e, e.type == 'ProxyAvailable').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'ProxyAvailable').all(e, e.status == 'True')
  interval: 30m
  path: ./kubernetes/apps/database/crunchy-postgres/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &app crunchy-postgres-users
#   namespace: &namespace storage
# spec:
#   targetNamespace: *namespace
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: *app
#   dependsOn:
#     - name: crunchy-postgres-operator
#       namespace: *namespace
#   path: ./kubernetes/apps/storage/crunchy-postgres/users
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   wait: true
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m
# ---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app crunchy-postgres-vector-cluster
  namespace: &namespace database
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: crunchy-postgres-operator
      namespace: *namespace
    - name: onepassword-store
      namespace: external-secrets
  healthCheckExprs:
    - apiVersion: postgres-operator.crunchydata.com/v1beta1
      kind: PostgresCluster
      failed: status.conditions.filter(e, e.type == 'ProxyAvailable').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'ProxyAvailable').all(e, e.status == 'True')
  interval: 30m
  path: ./kubernetes/apps/database/crunchy-postgres/cluster-vector
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app crunchy-postgres-stores
  namespace: &namespace database
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: crunchy-postgres-operator
      namespace: *namespace
  healthCheckExprs:
    - apiVersion: external-secrets.io/v1beta1
      kind: ClusterSecretStore
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
  interval: 30m
  path: ./kubernetes/apps/database/crunchy-postgres/stores
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app crunchy-postgres-userinit-controller
  namespace: &namespace database
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: crunchy-postgres-cluster
      namespace: *namespace
  interval: 30m
  path: ./kubernetes/apps/database/crunchy-postgres/userinit-controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app crunchy-postgres-pgadmin
  namespace: &namespace database
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  timeout: 5m
  path: ./kubernetes/apps/database/crunchy-postgres/pgadmin
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  dependsOn:
    - name: crunchy-postgres-cluster
      namespace: *namespace
