apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app portainer
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/portainer/app
  components:
    - ../../../../componets/volsync/primary
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: network
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CLAIM: portainer-pvc
      VOLSYNC_CAPACITY: 1Gi
      VOLSYNC_START_MINUTE: "11"
      VOLSYNC_CACHE_CAPACITY: "1Gi"
