apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-rancher
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/rancher/app
  components:
    # - ../../../components/volsync
    - ../../../components/gatus/guarded
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: rancher
  postBuild:
    substitute:
      APP: *app