---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app nextcloud
  namespace: flux-system
spec:
  targetNamespace: database
  path: ./kubernetes/apps/database/nextcloud/app
  components:
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: cloud
      VOLSYNC_CAPACITY: 5Gi
      # VOLSYNC_UID: "1022"
      # VOLSYNC_GID: "1022"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  timeout: 15m
