# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:hZ0p0ImeKyeFkYs8F2wfmCFArfe9Mlv75MviDLb6pJ29M7J7V8p1ew==,iv:g6YxVkoKZMk/GQXHNEEI6M7naDzqXJ8JmpAxvSKpsdQ=,tag:IDnY9S+eoV37OELVU+CY6Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFeElBcjU0MzVBNlhoOFJy
        Y1NpRzJlTHRVT3l6SDFiUWROWmM0TnNDbVgwCjBXTG1XeHQrT2Ryc2FxaSs5Vk1H
        M2IvL2NpSGpJenZzaHVyS2JxQ0ZpZ00KLS0tIG95bW10ZTZBWUlDRE9aSi9aSTBx
        L25rdGNzMXBwUGpYT3FJOThRaE5RakEKG5kH/wpT0OHwjFRfzWM8Tz/HJlvFXEqj
        2fps2MY7eP4vi2eKPdNKj6AtotWoIMbySPAFeDdt7tTxr339tjcaeQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-25T18:32:44Z"
  mac: ENC[AES256_GCM,data:uO8d3jUwlqWc1jyi19ipUuR4fT0ZNC75u8UN63eHjvmQUAFJ1PBdRJyS4ppjCo8Rm7RlAy1+VV7m+cx1dWgi3EMeeyeSp0CQWzwy5uYG1pgj6DbnVVE5wvVsTrKa/aHphkcJc1//9CzHiSjvoraEdQ8ZUphSy3/8Cs3NqCGmpJE=,iv:QV++sT+oxjILT17pcy3EtFfyib4bWvHjaEVZlanNUAc=,tag:HWzVpV6QUZI+PJKD88lnww==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
