# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:IBsOCgpIgeHq4qu6EHbO7tpqeP3UVvAQjuDBAcWrtosoJH0T0w12Hg==,iv:8/52mLQna3RmwhUXWqyk0S+LBK123gnqu6+Wf/iCZ9M=,tag:yrJOLI6BsdWvm/p5FaJCcg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRFpNMDhLcXNpRllGL1ln
        dGZILzNrQmhzMjl0Y3BHKzZ6NWJGb2V3MURjClVCNkxmNy93SWhOQTJnVWRzUDJP
        K3JQeG1NSGRsRHF5V0JTcUt5R0pjZ0kKLS0tIEpTSzBaZTlKYTNNclIxQ2ZMdmM4
        V0xxQTBWUk80VnRXdzE3Z0wxTXh3RjAKOI2UyP7dGz4CF9oo+IrtLPtn3xCIrpSK
        G5pJpTYlEvLjYFeeYjx014f8rHrZa74JFCqoc8KO8zjKyVh8aA2IcA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-25T18:40:26Z"
  mac: ENC[AES256_GCM,data:0TCoTtfMA7jnMI1sK/7LiZqVLgtfvBhd8MJo3c4NMlICyIGAFsv3GgxdLnTFiuozU+zw8NhxgBMyZUF63fyBEg0yXy3zRduh9TsbNXSU9URXjIZ4o9Ns9mdH0KuL6zmkbuSbOmZ90cc+adYZreUapw9CGPJHaPQsrzpsI07bsEo=,iv:TIIUGF1IV+1A18J11zWnDNreiV6FD/kPi7M9LzCnGBI=,tag:DAOXnzhUgqB5yb00t2j1YQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
