# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:pP/j2pmMrEzob/DrPIPpnlbF89vRik+lxvuWG7LSQbCKKm+mhEmGNg==,iv:SyEKBiE0EQshZ6irQ8/zxAWasZnkgbMJLn6SmBlaOQ4=,tag:8YVKUHL+/REHNnaD1DSUnA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0YkVkZVp1MzY1UFN3czJF
        eFZMaEhUM2pNRDJwRlpUMFl5NmRTVk5YWFh3CldEdkxZNWRKYS9wUFA0Ym5oV2Fx
        ZjFjZDl1QllKSStjeFZDenpSUHV6YnMKLS0tIGZJOW9XbENEYm5QOG8wYllRM2Js
        TVArRmx1UzdwWUY3dW95elBKYWNzQVkKFoVZcuxdnIaAijuFPZstIviPzjV6TrOX
        GElxCUXq0zCShbTEL8EBp0AXcYMQwAcjdc8Ki3k8gx/MXlgzlxCXnA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-25T19:35:22Z"
  mac: ENC[AES256_GCM,data:oO/0I0aSLcaXmwo1Po6JRc7VNXZOTlEz0uqgO31N3cI4DePjFnbxK6BShnPEPu/457Odb2hKtxY+udJ5OsVlkNtv1XUoc+YSUFzXkr3FS+qlGpXu7c+QkuClL+gYktZ1fdwemgh45JVPN99Spp6y09RE5XSOiYw3hG4gCX8MSVM=,iv:mVF6Nq3dZGIBRyFZtd5dYMnJvSVdgdcF2RWzS4TyGUc=,tag:nJrVyfY3cNfC0mZIrUuguQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
