# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:IzIxX7D4I58Y/y4XtHg3EvKdrj/I5dhjY3vRlADB0CkV0Ngiz8nqtg==,iv:t0ca765wL/uL/9uX8eGXz0mGJpGkIa9yr9vZ2Vb0b20=,tag:OVkeVTBaV7J5ZYfxO7lKYw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZGY3UkxxRjZ6NDE2VlQ0
        aXpuOGFvNDZ3OHhnMGZ0NHdjZFUvR3JYbXhNCldHaCs4bzJwSWoyZGRMVWszak5k
        L0w2OXFQR0JIWUp5anFwRGZPUDJHRmsKLS0tIEs4Uy9hMFZ0THZFZU1tVDhHY3Zn
        ejJwdGR1Q2YwdGRHMzRkVGcrSEhOTDAKbHvjwMvld9j9rk2syq0KbMfHDNgpr/7M
        ABIUsH2lwvT7V4qS1WI3pvokAOB1e6Ba3ImiY+I0rGe57tUHx1b7XQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-25T20:09:06Z"
  mac: ENC[AES256_GCM,data:U8HAXhGS9OYrT4PPEaj726K9kDloqSvUNTCw5TbyVaVP0KeuxtIZaC6iJ4I/X3QDUyiGXfdo1N19FmxHflATk6LmMEY00LbmMU+TU3AQcLKVaq3vjdLJk+T4u8dh7K6hunOJuLBPeFGCnZtgwXaxzyBFITIcF1ld2Z0LEgRzFsU=,iv:AaMJirNiaNvHGyvi7tuzjqmJFdxRUntYSShZI7l4u2k=,tag:1EbDxTdoSMUdlD0zo5ZM1g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
