# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:udZPXg/6OKr9lh7UR6KnjEY6sAT2q2PxALVat3IhM6ieIoIgiSPKng==,iv:95tkAr6QrOSYW9lwPCS0wUWByq288o283dINpfpfVOU=,tag:iMrr0dvCsOTUisT/4GGB8A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTlRXMENVNFJTSmlFZ1VY
        VTIwaForYzlSdnVPblQ1RmV2N1AwVGNoVFRBCnFhd3QxT2FYT2NWVTkvdDltR21s
        TmFiaURCd2tsZjFMdi90U1pkY0xzSlUKLS0tIElETzJBd0dPN3dQbC91ZFYzY3Vq
        N3AxeW5uSHE0eWl6aUc4MzdwdmtyUjAKaliScmh/L0xPfFTU4n76MhKpvTOH/UPm
        Xadr7c+pkJnUTbFpHnC4bn2nvosHj7PbbpvdJzOIuWSEH322NYB/Kw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-25T18:52:31Z"
  mac: ENC[AES256_GCM,data:jC+QT8cdXJYVXq6xcFLkuYo7XW97e5AidWBeNti7qvtdmiHFExhdfNQuaLrI5hXUkE7LUxwMZL6vj8nFST2EpOGZpKGAX6h2SzzdI0omawQb/+20HUPPBkdDD+laUTw88FTc6mrZIRpYhJ1K42lLxVh+56luGSJPVWxh/Cr+MVg=,iv:MTb+u7K2/sTj3SZOIaaTDwusMJ+XdWh5ADPRWrsFfIc=,tag:0IiPHATt4CicPjT9dKk4+w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
