# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:dTGQ+BtgByrOzfxm+pHpTOosJ+SkpxtZjur98vjlZOvoY12fthZT5A==,iv:svHqNJ0w2aYrowl2X6hTGYtlh0I8YgPOpr79+BG1JIw=,tag:YqKDDwr9PcyOXnWumjQRUA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrem9lekNyRzArZW5hcCsy
        azdpeGdVWW9DUVM4THdNTmFZOHExRHNoVkZNCnlJMHVRUjNiTmJBSDlESmlSc1dx
        MU9Md2JqaXk2NTQwOUdTUGdWRzNpa0kKLS0tIE1obkJmMnVBdXJvOURVdDVlcjBq
        SHIyT04yR2NLdG5TUGw4dnVlekxKUDAKmmyv4o11PIRa+5zjDDgPAQIxc3c5aDN+
        eA5q717EjzFnKJ91o4dI8inr1xv1Sxrt11cfbh26JLWwn9sBZEZqPA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-25T22:00:48Z"
  mac: ENC[AES256_GCM,data:GrNXQxu/znvRYzANi3fuFbe47xnsZe47KwPAwueXRgIKHSd2+nasF8JaGb+bxq9WxQFR1aAub/bxbNOJ0aIBxzyp9HUNESvOF6ngLrZavxMGifFkWVhMDwjTsKV02RZ3xWOXnNywwm3uUzpJnk24duIHXIBVrvjKRBOUY/q4ikQ=,iv:BAZ+eNS3Y8ADQEVuZCb2Rybg+FFS/PuVh1Z0MxQFIIk=,tag:4D7t8MacAIbg4DRDhQW34g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
