# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: smtp-relay
# spec:
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: onepassword
#   target:
#     name: smtp-relay-secret
#   dataFrom:
#     - extract:
#         # SMTP_DOMAIN, SMTP_USERNAME, SMTP_PASSWORD, SMTP_SERVER: smtp.fastmail.com
#         key: infrastructure/smtp-relay/config

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smtp-relay
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: smtp-relay-secret
    creationPolicy: Owner
    template:
      # engineVersion: v2
      data:
        SMTP_RELAY_HOSTNAME: "{{ .SMTP_RELAY_HOSTNAME }}"
        SMTP_RELAY_SERVER: "{{ .SMTP_RELAY_SERVER }}"
        SMTP_RELAY_USERNAME: "{{ .SMTP_RELAY_USERNAME }}"
        SMTP_RELAY_PASSWORD: "{{ .SMTP_RELAY_PASSWORD }}"
  dataFrom:
    - extract:
        key: smtp-relay
