# ---
# # yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: &app smtp-relay
#   namespace: default
# spec:
#   interval: 30m
#   chart:
#     spec:
#       chart: app-template
#       version: 3.7.3
#       sourceRef:
#         kind: HelmRepository
#         name: bjw-s
#         namespace: flux-system
#   maxHistory: 2
#   install:
#     createNamespace: true
#     remediation:
#       retries: 3
#   upgrade:
#     cleanupOnFail: true
#     remediation:
#       strategy: rollback
#       retries: 3
#   uninstall:
#     keepHistory: false
#   values:
#     controllers:
#       smtp-relay:
#         strategy: RollingUpdate
#         replicas: 2
#         annotations:
#           reloader.stakater.com/auto: "true"
#         containers:
#           app:
#             image:
#               repository: ghcr.io/foxcpp/maddy
#               tag: 0.8.1@sha256:55636d8a29588eea62d81d51acdafe38e0f694fb91801ab12dc1ed8c47b6439d

#             env:
#               DEBUG: "true"
#               SMTP_DOMAIN: "${SECRET_DOMAIN}"
#               SMTP_PORT: "465"

#             envFrom:
#               - secretRef:
#                   name: smtp-relay-secret

#             resources:
#               requests:
#                 cpu: 10m
#                 memory: 10Mi
#               limits:
#                 memory: 50Mi

#     service:
#       app:
#         controller: *app
#         type: LoadBalancer
#         annotations:
#           external-dns.alpha.kubernetes.io/hostname: "smtp.${LIMITED_DOMAIN}"
#           io.cilium/lb-ipam-ips: "${LB_IP_SMTP_RELAY}"
#         externalTrafficPolicy: Local
#         ports:
#           http:
#             port: 2525
#           metrics:
#             enabled: true
#             port: 9749

#     serviceMonitor:
#       app:
#         serviceName: *app
#         enabled: true
#         endpoints:
#           - port: metrics
#             scheme: http
#             path: /metrics
#             interval: 1m
#             scrapeTimeout: 10s

#     persistence:
#       config:
#         enabled: true
#         type: configMap
#         name: smtp-relay-configmap
#         globalMounts:
#           - path: /data/maddy.conf
#             subPath: maddy.conf
#             readOnly: true
#       data:
#         enabled: true
#         type: emptyDir
#         medium: Memory
#         sizeLimit: 1Gi
#         globalMounts:
#           - path: /dev/shm
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app smtp-relay
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      smtp-relay:
        replicas: 3
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/foxcpp/maddy
              tag: 0.8.1@sha256:55636d8a29588eea62d81d51acdafe38e0f694fb91801ab12dc1ed8c47b6439d
            env:
              SMTP_RELAY_SMTP_PORT: &port 587
              SMTP_RELAY_METRICS_PORT: &metricsPort 8080
              SMTP_RELAY_SERVER_PORT: 465
            envFrom:
              - secretRef:
                  name: smtp-relay-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile: { type: RuntimeDefault }
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: *app
    service:
      app:
        controller: smtp-relay
        type: LoadBalancer
        annotations:
          # lbipam.cilium.io/ips: 10.0.42.123
          external-dns.alpha.kubernetes.io/target: smtp-relay.${SECRET_DOMAIN}
        ports:
          http:
            primary: true
            port: *metricsPort
          smtp:
            port: *port
    serviceMonitor:
      app:
        serviceName: smtp-relay
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
    persistence:
      config:
        type: configMap
        name: smtp-relay-configmap
        globalMounts:
          - path: /data/maddy.conf
            subPath: maddy.conf
            readOnly: true
      cache:
        type: emptyDir
        globalMounts:
          - path: /cache
      tls:
        type: secret
        name: smtp-relay-tls
