---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
resources:
  - ./echo-server/ks.yaml
  - ./smtp-relay/ks.yaml
  - ./searxng/ks.yaml
  # - ./rustdesk/ks.yaml
  - ./it-tools/ks.yaml
