apiVersion: v1
kind: Secret
metadata:
  name: onepassword-secret
  namespace: external-secrets
type: Opaque
stringData:
  1password-credentials.json: ENC[AES256_GCM,data:Hz+qYRYpvlrLnMyXC45QjdH4Y+5SbaYCd+6OlIzZRYa3vqLcAGhF4XOPqs2IKQdmYIaVy5PtpoY/07eJxiIa3uD2lu/CkTkwI+vth8PPeQOPiiNP4ZQ/IwqosR0BgO5oSLVDLLwU4qy44RwOhU8nR6D4AQUp1pYjLcwBdGdKeGVu405+RIrfI8pmchhvvzt6Hkv/MP0ZcQtqrfunZ9N4qsDNjc48CFPV4ku78D5q8k4Dzv7fTVgvCD232+1K2cl3ddbxiFHp+lMgi98P64zRzDOBLPmtJS7vsEAtGt7/2Kc2oSmiVGxuo3XfX9Kex3dtE1HE5mtD4ILIfWaGGIkyDRJ2+RM/iqYfTaM0SqSWIVQ1aeZKprJrLCvsKCTUaFXyD5NnpwkExurjWdvG0UnzizKy+GSGN623qdOu4GdfbnhFgExihS/F2Fsnpm5tIobxlMBDyesVuKZVnoeLhJUdVZB8lFFz7CuxbqU3OdUrSjxhVDA8GY40UL2br0BmVr5zQTGCKjxQhKunKKdmS1EPJqVBBcfqMTl9EnkRkAbMEOd14nJm2n0CaXl4iBA9JCUfuofCmuPGO/G8IEfYhPEqIkrIc+7z600z7IMvR9DtBZjqK2KK5UwcCO5CXk0B0hUXjkTIOmUdQLpm9q9li7BHmXcJ81e5nusI/XhQsBwdmhlTQC672AEaKgWNefix5tj4qpC/pOuMbGWfBDbjRTDMaHFstPTrU5eVQ6uszvchHZIL0bkg4NuZ+0xkzq94c9IlWPbE6mSBxJq0AOqXnAip2Vb7xSaEF3NP8AhymNid5SM43gNZFrYAEflNDH42iccD60wPcTYfDaNddMIu+DoS06QJUYz5uqPoXv9Iss8s1mGyN2t2whabi44H9kr7mwLFDV0Moa8nF3bdsYAzpiiydGDvyJTuc+CTmi2dPFExrk4HpSKe6h8IMv+UkteOjLGEmKjXaYLGENQ4Bnsw7nvyJzv/FbV/Gi/KqMDyq7Y4QQDap5u9FA4Q6O2yfBaULsLxVOhuTJos5IrZS9BU/ZhNQsQ6RXjO9Gp6GnqAzxWP4BZeSprTvDAdlXE+CfvGQnHmGMQE6EC41+W4FepGggbYF5+OVRV64LJ+15UZrWdZ2x3p08DIlxZ7rrG7muJMnfkWIHMA3CjTAKVMWimr6gRFcXik0QtWqOqOMVi6VbOmJflPP6auzqC2/0Zy4PCU1LYtEBsfmkgj4oo1HkInOBciILIzBvRG9i3sGrYxPFtnGvnumwQwXOX8yvpWhqeY7pQ+iDFQEyA2wofkiJXjYBI5GoxTR6kUa76TSth+CHbnDdsabXwLwFEJxrwGNb+reqZBHpt+n1iby/c6ZICqQ2+EbkMH6N8DK449RibfHRPzwajQM2s17ETy8YbcnrRuItrgZj1tCSbn+vimi4DHQFp1aejD9OutuBadexx6Xx8YWPxogfnVw49h3f6aBMy1799LaBGogjE+sXlef+8hWeJzIrwDXdIh+lv/NMSmlTdTwu8anLFZPeeTI4KG4nU+TqYEGElnF6QRpeT0AeaIfod7Aln0lH2Ig0pUjBepazc4TiAEVkn/8xiXNhVMK4W1Ky4tnM9NuIP0DLHDNI4UT5QGPBBqVwgoizArUo2hWTuirTlbMGxPCuyBXEC2y4zb1G/FEew8l8PRK1CNF8s+saDXn5DcPANa12o3PjdJ8Jzk+MsEoCR5ibPdfduUznmWOdGaWWwfcKojbJkTdbojdIE4+qeoVQrVaLd5w3y7D283/S5DJjPWIDevf5QwJu9WSYc9FjnmhP5LPmjLq0Fseprjj6M38Crhk13nNcXJ1bJz8QLHfdXfS6+rs/cm/adFznemapov4QrWah0FI0e/d4plWOsWnQJDwyT99ht5n9xXuNwFtfV96FxMVBdJ2KfVtqfowGvl2wUw371gPAYM,iv:n7NUtN2pZRBXsBctYD5RUEvnxhGuU2d8nBWANl0SNpA=,tag:LO/QaHwq5QQX7pCJ3fULMg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUldnTnV4UEtieWJpSjh1
        cWNNRjBaQlh5S3NVdk53S2pNdzF0TDVUUDFNCmpETU02VGg4L2g4RHNuWS83TWNR
        cFZHOUhreEZ0SVcvd2NUaUFIazJ3L0EKLS0tIHN2NWVBYnJqdnErVlNCZ1BOd3dM
        ODVidEErMDlpNjFUK0lGUGU1NDlHY0kK448AJoN4PWt+rmpOTfdkPPn2O5aLh6UD
        CeCFK/cd3qVn9vqpS92oiQ4uXxj7NXx/fqKzPWXM3DzQ6FNJm/i3CQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T20:23:18Z"
  mac: ENC[AES256_GCM,data:f2sdY8fxdZFCaAjV9Cr4aXDdWBAh739s5JRm5mHJ224ivbYu9y/jJPjL+VRk6EidqjXzGFRbCYXEdZyFLE+pSBcaxxdckjG2GThMwojYnZ6TgarZ5YwbXs34UwRR8qNn5VA7lD+copU0ku0cYiNZwVfV/eIXhU9kwY1v0igDjPw=,iv:3hm/XfgIne508k4VMjApeET4DqTCnHBDYubxSk8wBFs=,tag:wzniqT5U/PYsQIbwidwPBA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
