apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:cT+RdUHIRQkOZA==,iv:fSKZ778RBvr1NuppYIB6sx5X+eppGRWgPBhojGc/VuQ=,tag:EeyHHBDckbGjQ6/D0hZOFA==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:1t1yweYMvkYCRlYUMp8Opl0MwETSSbbcRoSeTZryzy9K9wo5,iv:aR1jBV7H+VKRwb3bcQTO86Um29lwZp5Da795g9A6HIM=,tag:ck4gaq+VidnOpyhI2BwZUg==,type:str]
  SECRET_S3_ENDPOINT: ENC[AES256_GCM,data:DcvPnq35S3N/r2MZXULc3rcUwCBzEJI+lAirE+/oFysYh0Zk,iv:P2dzcjcPk8OZ7vGqgzIAEZtTzrRYNE8zWZ0y6nnZqv8=,tag:gNuYKmb+9zSM/aS2NAMHdA==,type:str]
  SECRET_RESTIC_PWD: ENC[AES256_GCM,data:YokYxkGrIFtRNBAM,iv:n4t7kkOaabtIxp4xVMA83QlNqBK3cvLaG0RBSQlD3ZA=,tag:juE8BR5Sc2zToWVFCw1qrQ==,type:str]
  SECRET_S3_ACCESS_KEY: ENC[AES256_GCM,data:4Od2eYN5eRhsaOne7BdeYrQwBUE=,iv:qgugPX9gOXWeH0wxjguXj7qR4QJEjUrVR+wrC+dFP8s=,tag:zCppL3N9dTcimUTvGhfZuw==,type:str]
  SECRET_S3_SECRET_KEY: ENC[AES256_GCM,data:UeTR52gNm8nQ6Z7ovJSiG2/tu5THwYlg3uwu85CDyRNtrhXj2hsbMA==,iv:DWY/leaszA7Ou6KTI/8SX1fCa8d3ZTDS83CdoFb0atI=,tag:dl0m2aTCQsSqTNG6cJEKhA==,type:str]
  CPGO_R2_ENDPOINT: ENC[AES256_GCM,data:hVcz5gkytEqnOQZyKmIe8+60K0lpojUQgYREfKhiZAIprh61nZ9q6OU/y8+G2zqnW4aDOO03ZwRWFWhmveZGo0gd,iv:S31f5YhVnvvgrNLYCL8meqjAXqlRy6oc5IOMFDAShU0=,tag:8dy2Ob59N3qtTNYRlK0aKQ==,type:str]
  RANCHERBOOTSRAPCODE: ENC[AES256_GCM,data:KPBiR1nUxn25bmYS8hQ=,iv:1mZmBEnP/LyPE9h9Bf5UAC5TwZbvEUCwrcxPyHIoKgc=,tag:3P0zp9kKF97BCvbgThvKCA==,type:str]
  PUSHOVER_TOKEN: ENC[AES256_GCM,data:3OlnRDgUO+li35sbkVJHSiH3OPgfTkZBqdnn1mL8,iv:EbkJ8A+6m4o7jnTDl05bZRszeg6puftJlXSEagr46LM=,tag:NCOdLvLbRQ3T7gfF9zN9tQ==,type:str]
  PUSHOVER_KEY: ENC[AES256_GCM,data:i4FUK+3c1OPSqUIcxdtE5UhOpTRT+b37GKPwDOub,iv:foCR7SSYviJg7x6P+wCnwxKOoXui6hfUKriM9HI9KYM=,tag:+HaSHmh10i7jnPnahbTNsA==,type:str]
  NAS_IP: ENC[AES256_GCM,data:Sn6M7m/qLN7sNYQ0WOk=,iv:WxPsTkcL9ZPiaCroR+L/IvY3/PeMixJZRv8+zSHHOgY=,tag:GqbY8B40wVSson/qKVug5A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcTIvL2xYTlRWWTRGMExO
        QzhKcDVjdDhtdVYxSzZzT3krRS9WOVJBcmowCm5XZkpkU3laM2hPaVNqNUJRTG40
        SytwM2JUd3I3ZWU0MGR5SjhpbVZOd00KLS0tIDhtYVppcWZwdGdPMkVkVDAzK2xs
        MVc3QUN5b2ZEV01nUHVMaTBRS1ZwTU0KeiNfp8lblSIKWwMA0WrF3YOWlMJTW0jY
        lSVHgenfQ5EQebUDT1HwBSMFK2HgqzIlg9BuxWYeWZHiixI1ZI7qLQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T15:11:15Z"
  mac: ENC[AES256_GCM,data:zgEpY/sSgQrs+lpeO0zMF3LcFFpjG1f2SKR+m41BQVfxD+gaK0WQAmxL3wuASIrUEi2wLRvbhcWBC4L19CV4m5nzAo93UCK5HtK1ay6EgCt5pF9LOGAkwV1xNALyc+IXeBMFITCsl2hMcAK4wIOw6VgAtw3VSd1uKk+ov3qQ7Wg=,iv:cZ8sup5FW+LCpdJPI1akF74Y8OraVVrdXto32TB4DEg=,tag:8YU5rYdItNpx8o/iCftjUQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
