apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:VPRiz1DwKqg2Nw==,iv:D4+aMWzsl8lQZiaO9iGPYKeQHcRxXy4w1aO96Z/aM34=,tag:RDkZIg0HLNrlCrN4TAbnpQ==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:ZjZh60FjtMEehnl0l4V/DCVxooiGXbBGjdvIcGp/+e0OJ8gi,iv:K8vMGoU0oCnHCsGM32qff6DATIbVX7wbYBXj8R4RGKA=,tag:p3eWet7DGxq5i2zvSAMhqA==,type:str]
  SECRET_S3_ENDPOINT: ENC[AES256_GCM,data:k5KoR5epTf1EfBjfsOYKnCT3RM8VyOQC/AfAKaBcSsIjQzm6,iv:pfSwLXT1Jp0gMrZITg9mACMc3j2w3l6Qmd4I0mq3jDY=,tag:C2Ot+6QVfS9V9e29ljwXvA==,type:str]
  SECRET_RESTIC_PWD: ENC[AES256_GCM,data:bA+NDzoYfwntwdzm,iv:/sghxFOeQVqimaAa1Njz0ZUWO2io4GQzmXcNc8FEhdk=,tag:gD6e6Boj/3DRaMY6BC6g6w==,type:str]
  SECRET_S3_ACCESS_KEY: ENC[AES256_GCM,data:WHgLTABfBvrcttVMPX+/ZbXZny0=,iv:Q9Go8YRqgGsTv+XqoRQcO4S20Ohmr3QcRCzAR+rRFfI=,tag:cTVA7ph/QISuLvYb9tSgFA==,type:str]
  SECRET_S3_SECRET_KEY: ENC[AES256_GCM,data:vmPy+SNz8jhiE5kcs/iOZyZu4nEqSwGDb3XtkESrL70l6Ky+tPunlA==,iv:VfSI2IZsJ7pE4YW8TnlRNlfab8n1GszKGWxwJzuBGEs=,tag:FETBSXkWxtkxcXpnnhN6dw==,type:str]
  RANCHERBOOTSRAPCODE: ENC[AES256_GCM,data:JOYW6Dgl+P7zvkfMqCE=,iv:M3SxOzhR8lTjbYoJfwUVeCx1GCRF+NFEZvAllg7X/cU=,tag:+84PCf2iq4wx44aQt6lD8g==,type:str]
  NAS_IP: ENC[AES256_GCM,data:ubkYWNQzRAwJ5SfuEEw=,iv:C+T3tuvRrmYEVQjGErHaGoivAsFldfjd8BJDFGsVjJs=,tag:R/jBv3xHehM3ML7L1ZwbnQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNWhucldzTElCWXFsZEtC
        cjhrUTVmblpVdVMweWZIYkhUU1YrT0FkWHhrCjlaV2ZJeC9wVnhLNlZnTGhadTRa
        NDZiQ3VEMWF3aE5WU1M5TTdzUkhCMjgKLS0tIDN0Y08zMzhkdWltb0RlVE5NQ0Z5
        bkVJMFFmd1Q5LzlIY1ZZVHJVMDVyTTQK0JFM1GyW75rOlE15hSvPKtsjFowiAIbJ
        0N4i2p5DKap+7X8Td4RFz06n5t6AxO5vPCK/60OHm943BF2plgWabA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-03T18:38:27Z"
  mac: ENC[AES256_GCM,data:CTHmztiE1fFJBuySt7O1v0ADZrwOAjz/aTDE7hDocOHoc+m1tNHM2mw/kTeeF2BO9E/InmaAcM0VZHWCnWRLfPnRWpMEvYr0V+KZdVUDw7WkFena027hWtuxEWF6OZ179huFzAheGu3VGnnSZDLheKioowv4dAYNEpmcF+Rpd+U=,iv:BGL0cPYBT7w6sxw4sO4JbSYwNoVy9+9hgBIcz6mn+bU=,tag:Jnj/ZgEe8iRuaPOhxz9gOA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
