apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: hayani.xyz
  SECRET_CLOUDFLARE_TUNNEL_ID: 175ba056-920f-40da-a12f-fa512dc7422f
  SECRET_S3_ENDPOINT: minio.storage.svc.cluster.local:9000
  SECRET_RESTIC_PWD: Luvh3ng0@345
  SECRET_S3_ACCESS_KEY: 9LGVWp2DGU02YMGRh2yy
  SECRET_S3_SECRET_KEY: 01DyKSoY5dPuGYenARRYDKSkrJXRtWO4AiqsB3v7
  RANCHERBOOTSRAPCODE: Chrisadmin@345
  DISCORD_URL: https://discord.com/api/webhooks/1261085857734197320/WaLqd-mqTpqTLyu4iUnrLJ-0NPzUH9VYDM-Eb7lkew3war63NwQRZV_WQ3d3VWXJRIfn
