apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:oeRZofvIABqILA==,iv:Syzcy8c5Tsslmwwk1bDcqaXP3ZfbbWgqSi/3kbeJRoI=,tag:6ZyxVdZhRQ0BEjHq44P6lg==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:N9aSyQGZj/YT6mM/FPAF/YVE7JGg5wWFSoiKaP+JaHZloei8,iv:V+hlgWmeuXgZXBnU19Ry9FD6Z4/+++vtMeJERjFOUAs=,tag:3BitKPEExN4UBfFtwy55Xw==,type:str]
  SECRET_S3_ENDPOINT: ENC[AES256_GCM,data:pYrEM3K4fjfkniVKs5qmjQ==,iv:RCOBPJlEL6Ti+RUn02LlULW6ItPPKDj4k8hXYkTSxjA=,tag:zyN9z9ebShVma7W+y56krw==,type:str]
  SECRET_RESTIC_PWD: ENC[AES256_GCM,data:MltCcy2J+RuNhPuR,iv:A4w/L8dZUCszRzA5q+Y1hSNsZ/RRUrub3eD7G4fWofY=,tag:OAxOY+KP0xXZ//Xds1WhmQ==,type:str]
  SECRET_S3_ACCESS_KEY: ENC[AES256_GCM,data:DGLZ26aaXfnX3Zn6WJhPBKAhI5A=,iv:OdJKmT78RO/IaL/4X4UT7ZGPqyQQ+oQKhZ4pgFraLgI=,tag:exuXAFsj80htBAYT/1p9JQ==,type:str]
  SECRET_S3_SECRET_KEY: ENC[AES256_GCM,data:WvkblSy+nbG2FJdoxvVRZpPCS/qK70kpnOK4tVG/zdLjoMeeK84cmw==,iv:lrKyhxBVUdQ4ma4UcebcNXIVJsO5y25lsaNa424/SOU=,tag:ndwgB07nM8zby/DWODJ03g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIT1FTMlFKWTBXUzkxUW1W
        b3NIYUMwOVVjZU1vUENpTlFMSVcvSmc5d0I0Cmx0NGRqTXlYdE1Qc1UvOGVZK2Jo
        ZmM0QUwvYUR3aEtwL2d4cWJ0c1EvRWcKLS0tIGdScVVGYnh1ekRJOGt2RWplUFRh
        enZNRUxBak95M0g2Q3pzZ2ZwT2hKb0UKZWw1Jj4g0fRZxWtOR9dqdKcadb+C6Bnp
        LSJkXSVv/Lda9OXi4jbFHqK2aGOHk39R1BO/++XuM2Epe1NTOS4sPw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-27T11:32:26Z"
  mac: ENC[AES256_GCM,data:YfBSywmgAK+PLT0ClDdAIBvofBAM30RayWWiAb/toUd687BwoCtVVMOhqi9vGu7X2OSPcOCnLAozlwVDcrYEoVIepPLI966vESHQNvOP9+uHMASkKUr8mPA8Pr+cJW+E79UxejUDB9n7+zGVezQfdI7mi/05HrA5vdB7jq/WYjg=,iv:IxuYwb6nZZD8slHcOt9SNqna+rNQyAqmuPadM5gvqPg=,tag:Y/3nj+iAjQuQ1T9XniBwew==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
