apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:G+vBNeOPt5ZZZg==,iv:c449R04GHieOQxhZChwYWsd6oynRqMrhPAhs9Tvijec=,tag:yKqGTZUw50IQh/zoHf8fZw==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:bJxpPR+MdEtF9dgL34ZHHE2EbQCRXV0qTwyC1Ywf0uQg0ZvH,iv:cYaGFAmeVnmAS/eIlmgtL1dJjSff+YZT264Q6oftwdA=,tag:2Iw1sZCesvDnz5a+2bEM3A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyaEFnN2VxNU9HcE5uQ0lF
        OWJreDA3S1oxd1ZNMW9mNnVKa0k3VVpQOGtNCmRPUytQV1dzK0UzZWRSVWttcExa
        cFBrSE9kbWN3VExXSEVaM2FRNGpXZ2MKLS0tIGdkRCtoMm1WU0I3M1NSbk83TW9y
        S3JyV0lOYWJ2R2hOaXJFVkFRR0IrUVEKUmKfNt3BfA9Gl6EPOK9bxc30bxrdJ5Ua
        aQQDOe6Y31XT6QumLGXCIA1MwC00rWkyJLP/0xL/AX9UwoUd46mQgw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-25T18:32:44Z"
  mac: ENC[AES256_GCM,data:eoReMZQtvPnKXPxM84ZvEqvexVwXTifYLrHAjVbdiGqFCH8ahWmw343YJ3NcjQ5gXmGqVGjKSJ8hsIJa4BI0XxcKkP1W4oKsfEpesp8mr2q3W/YvcXfxPGodnlwbwrNhXTSdXUzGS8hkZgjema2vWbm5YPUjtDGDMILmlqkCJtc=,iv:cLiTfZye+KMDwMzge3Kwa83jy5/zDOInw4tkWioBCLM=,tag:Z5PeGXaNzhSilxRm6Ir5hw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
