apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:t8rWl1LUb9Vnag==,iv:IjXnaBtaO7+hWqi3Ax6zylMkdY13nj1NmI1YW2Jydt4=,tag:Rak2F8D849/5kH4htTUmIA==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:X+9NRt81n7wYvUP/FDJgP0+ljpml5z14/S7yu+xVNR3f5Iw1,iv:LpqWHlI1kc/etglNydgu9277ZNERQNRE6c4aa9Htgf0=,tag:6oEfjkN8hJQT8k1DUIkrfg==,type:str]
  SECRET_S3_ENDPOINT: ENC[AES256_GCM,data:+Y6XqPTGoK90wW4NmpCzJ0MShSJrKyQl8ObfkL5Y7UOkLlDa,iv:239FtZPmQv7iS53PgYXKHQzdXeXB+68JzskbX2WdJ1U=,tag:z3kZaYkCQ646+eL7YU9wmg==,type:str]
  SECRET_RESTIC_PWD: ENC[AES256_GCM,data:e82IMKRgwq5+yXfw,iv:QP+g64iAomvlcOvtBvuhlLCJpMnSxZkqKnOWGjv91Cw=,tag:tcycahxEPfKqKwrWKRMZQQ==,type:str]
  SECRET_S3_ACCESS_KEY: ENC[AES256_GCM,data:vJ3XJU38OM+nAYDIgk2Msilf2bE=,iv:vvd0LH0icyvZxQh+j+FeIV7oyCgVIS/dS93W4QuD8z0=,tag:rLQb1prgAHWLotRjYwJ3HA==,type:str]
  SECRET_S3_SECRET_KEY: ENC[AES256_GCM,data:6IFZHDmLnd1zgfd3iD2dt8ckTZVh8YHOd48Cuzrk2Ux2ycrwoJnoXA==,iv:THhE68KAA3DUkb+zDs9QHwuqBskqeboqaCkH3uAoQ7c=,tag:IBisnd6gN0sHTYb143FazA==,type:str]
  RANCHERBOOTSRAPCODE: ENC[AES256_GCM,data:pgtboaNmAk8ueHPy8TI=,iv:zdfFhwTDp7Mfeluw6hkfxTO0uVLHMZcsmMdGuIDD41Q=,tag:Kl9QvEmIeWZ05zkZFMjg8A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrL1BRYWRwZ1NLbHFBOFh2
        N24rN2NkY0xKbUxJY1Nsc1E4YklvYktVbVNnCjhJMHMxYzRHa2ZacTVKQUZYdDBm
        UGpNaDlNRUFJZ05WcGMvWS9xTDhSeGsKLS0tIG9GL0dlMGpCZnNETTQ5VThpaTla
        a0E0Z0x5K0J3UncxUlpWUTY0dmZrRGcKJIQnjpzan7EtmcDsODWGkJME0re+N+Te
        Xf8H/5KU7WcmXVmbKFy1fECH/ZFQtQ2/1W0dbpWOgWNiGBoPXFHRiw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-01T21:42:29Z"
  mac: ENC[AES256_GCM,data:+QwBA+nmzH0NyFMfRoI28d+Ay4IrRSbRAXAyQEBZd7a2UGE4x6OLnc+R0ti6DqtQc/LIwuaV8N6QC/jc0rTIQvhAOvIvZQ9V5i7wmdEWV5IXewW54PGkKV0v7DcucYpWpzOT/Oti8z/lEuXb1eVNKnHEq7d9jw9M9XI5dbujY6Y=,iv:f+XH8aKDPw5hCnTJsfcRYfiBpo157LdZT23XbH9OAyY=,tag:wRxbEt9c9jQg+GvpZiymDQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
