apiVersion: v1
kind: Secret
metadata:
  name: discord-url
  namespace: flux-system
type: Opaque
stringData:
  address: "https://discord.com/api/webhooks/1261085857734197320/WaLqd-mqTpqTLyu4iUnrLJ-0NPzUH9VYDM-Eb7lkew3war63NwQRZV_WQ3d3VWXJRIfn"
