apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:9R9Ge3dr0uWct6xh6D7ncQc38Jw5C5KmMTpgvxcufTX2PbSLwLXpOsCIvlZGJ+uPeQ2s4e4cKaNItwh7DqA7GC3vaTO8I2qAhbBY,iv:aLp8LAFp5xKly0SC/CZ8kIszKm/ivTM27qWTDC21LEI=,tag:qRqiYyeqDTKCDe5ikzgIFg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMEhoVjZYYnVSTDBRdHNm
        akc0MnZqUUZwcWVlK3VVVmdZOUxLL1BrU0FvCmNkOTZkK2FtUWs2b0FpSU5IRjgz
        Wjh5azluNFV2c3JmZDRSM05ramFyeUUKLS0tIGVZd1FWVHlGeEZ3YWZCSXA3TENz
        dXNWZ2wxT2hsYTFHdzZsOXovL1pQUXcKALLLyZLXmPvFZxrV0yuPl5QgqAA++5oQ
        isGJc7I5BaIzSzJ+BOvZtoKRBdxANMxZjvh2D0ObxaAignwHUn8prg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-25T22:00:48Z"
  mac: ENC[AES256_GCM,data:9LNqV3NA3DIfJRtB5BKNpa2QokOiCP/vvYlbpZ99Jx0GvgxnMop7a7Mom7KKCzE8gRq2ZXhzQAF6S/4MDR5t8TUicyeek7wUzJ2ulcxcGpjRNhmmJ+d9QFI3CbJtbjb1EG1dQjjuvAsPATO6oiZjW2zB39d+fYTdjlA+HmUhWao=,iv:rDfdFhL6sTMnBYbuXaZqQW4zlgM3WevkOSahSsxyqZM=,tag:Cm7xXiZovGuFGveHrpcXPQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
