apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:xQX4Izg76JpLY8LbbokjPP3RWAam8ZEKsulKEVWIsMBzia6gvRJ/vTyhz0liMPVWLhEDN2PRrYuPumrotCEx2r7JLL94RF372rFZ,iv:AGCcGMj4U/D4zqn7MiNqMobhoLc/NNfh6RCsXmL7+cc=,tag:LMwiI2M6W6DLbDsMA5HjXA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OUxNSERjZWRSQW9UVnpw
        cjA1OFNpQ3VQZXlFeitkNVltRDFmSjkyVFFvCkVIZUxSdlQ1VThvdU9TUTdrOEl2
        dzZNZFc4OE1MK3gwaGFEbEQyME84VU0KLS0tIE9DellTRVJpV1lyU1BLVTVOM285
        VHgxdGhaMWpRcnRoemZ4UGdDWnlEYk0KEPbApAbqm6pRoy0nviHFBmP26KvFlJ7W
        CR8hA5QJodiCyPbbfAi15W38ySPz45pD66WiuKFkOI9d0DcNpuj+SQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-25T19:35:22Z"
  mac: ENC[AES256_GCM,data:CAkEPaLvI3XM0WaB0i3sBcqcdy17pA06XG7zYdxbikfCG+c9ldVLwlxEnzDmSvBh7ghLECmsQAwidQCtYLpoyNsVG6Bb0Ef7fbhs9crtbyBGLPD3YZER61HrjaB9e14Yb2M0DHbY27HlelJlyOgUkDHz0Dk8u1nG8mvvEQ5fU48=,iv:K7NEQt309/SohGl7JHUVkpoif5p5IiO0z7hO29AJ2pU=,tag:2VLYgyCoe1626dddSqBBXA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
