apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-redis
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/database/redis/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
