apiVersion: v1
kind: Secret
metadata:
  name: discord-url
  namespace: flux-system
type: Opaque
stringData:
  address: ENC[AES256_GCM,data:0wydCZYCl0p02xNDZ6Q72tI01KS1GMIE8AJLlxzA+Pm+he7hHERRg9JAuCN6nMLPfbQG9k7uQ33UJYtxS3TKRut1Eldt7pE3BntOPkHbPcw7GTh/oq64rbQQRDCeFaZuVyU607OOzwIqaPn76NQIwjTcRAcrwEVMpA==,iv:S7rSnEKk4AV/KuTthNQ7Jbeda0ZvhOhLVNwOGjx9t2A=,tag:S4+nz3F/n0h3q7Am+HWp3Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvY0Y2VVpFbUtaMFk2WDgr
        MncrUzM5TU1wdWtaeW5jZEhWVFRocW45QXhRClozcEpRTytpbWoyQ2NqTEcxQ1Ba
        T1VkV0NJckNrVDBKUVFUbklvTWFEb0EKLS0tIG1qWFptSGRhZ0VQaEVrWDFkanRv
        YTl3MDU5OURIWDFScWpVZXpWSDcwSUEKw9fVH54VRnSojmn3z/e4rqOr0LvNVh6t
        mttVckqJcpbzjdDM/VbvOHOTMa00GEWfftn6Ay9pnjAEMT6gqPMmkA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-01T18:37:06Z"
  mac: ENC[AES256_GCM,data:m8DduQ5cOqYY/O0p4ogkUXUtJbDGxymdNDS7WbHHMFJEwCeG4oCfZPw8LzAK+FkSsCRpxmnXZKmbIRwnSG/2vQTmdbb/9EmshI01aufgxPZzc/M0NBK5g7gqzED9YFH0PP3MSkRMl0ANcriZl9AGfMeOevDKnDNZzHaiQdaN3qM=,iv:icqOBro/MEwZsTZ+fRkd45c3GZYpdmL3e/3v2g2Nnm8=,tag:WBjXYxHAcSYQWuhXiB47YA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
