apiVersion: v1
kind: Secret
metadata:
  name: discord-url
  namespace: flux-system
type: Opaque
stringData:
  address: ENC[AES256_GCM,data:Iu1Z+MN/ctMHIf+N0AGGytnWPsTDNj8TwRoDVMfSLTYPDMPS19497afcdWMtoULbUgvWvraQhwW/QYzIF6se4l3LckHaalJ4gzHmTU99abMHhXtHdScMLWUyCFPRDWikfAh/XFnCG+3kBtxB7QNcVTiX2MbQ9aMp+w==,iv:KK+p3Uaii6uGUtPT9LmZkMQVmqhsuBY40naZJuFuqd8=,tag:Ty3hj1VVQfMwqRt0/SbpoA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TUNUSENqZWhLQ0toMjdx
        K3JZTCtZcmNod3RSak5vVjF6by9uTzdwNGlBCmJWSkd3RUk3OEZXOFRDU2dHSE9L
        bDVJRW5kdlJ5dzhjbEpQRkZ4M0t3K1EKLS0tIFhYR2VJOG14cm8vVlFyQkJ5UG53
        VW9BdndaQUdwMnJFQnovdGVIQjUvQWcKssSqILbuDshPqX+GYw6qQSugrwMtkJrm
        75xy7zr+ktaOtTu9q3GY914tsCPEm+CiJ0DibRoi1WZIIt+5EW8k7g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-03T16:05:08Z"
  mac: ENC[AES256_GCM,data:TuVr5indWLamOdSwK7fDbQJpykZy9iZhSZ723LT2A4znGSXqvb3jTQRZqrxeoQFRTWMxBCWVQHYZHvEdPX2XxlrclyQcMVfqKzPvGNp/XAx0GsaVHf7MLv7Q+zvxJwVb2YBAyB2SKlSZL3pVTRxPrz4DAFvnPLkrYFO/f2B3emE=,iv:/Q8J44+AF+bJpqUjwSYmhBRRqghJv529LzeoA2/2AWM=,tag:7Q38Ur0/8FRZFX7LOF7HHg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
