---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pgadmin
spec:
  interval: 30m
  chart:
    spec:
      chart: pgadmin4
      version: 1.35.0
      sourceRef:
        kind: HelmRepository
        name: runix
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    nameOverride: pgadmin
    strategy:
      type: Recreate
    env:
      email: chrisadmin@hayani.xyz
    existingSecret: pgadmin-secrets
    ingress:
      enabled: true
      ingressClassName: internal
      annotations:
        hajimari.io/appName: "Postgres Admin"
        hajimari.io/icon: simple-icons:postgresql
      hosts:
        - host: pgadmin.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
    networkPolicy:
      enabled: false
    persistentVolume:
      enabled: true
      existingClaim: *app #${VOLSYNC_CLAIM}
    resources:
      requests:
        cpu: 15m
        memory: 183M
      limits:
        memory: 283M
