### NOT READY
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app rustdesk
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  values:
    controllers:
      hbbr:
        containers:
          hbbr:
            image:
              repository: rustdesk/rustdesk-server
              tag: 1.1.10-3
            env:
              TZ: ${TIMEZONE}
            command: ["hbbr"]
      hbbs:
        containers:
          hbbs:
            image:
              repository: rustdesk/rustdesk-server
              tag: 1.1.10-3
            env:
              TZ: ${TIMEZONE}
              DB_URL: /db/db_v2.sqlite3
              RELAY: "10.0.10.25:21117"
            command: ["hbbs", "-r rustdesk-hbbr:21117"]
    # Because using docker host mode
    # Just in case you forgot the ports:
    # 21114 TCP for web console, only available in Pro version
    # 21115 TCP for NAT type test
    # 21116 TCP TCP hole punching
    # 21116 UDP heartbeat/ID server
    # 21117 TCP relay
    # 21118/21119 TCP for web socket if you want to run web client
    service:
      relay:
        controller: hbbr
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: rustdesk-relay.${SECRET_DOMAIN}
          io.cilium/lb-ipam-ips: "10.0.10.21"
        ports:
          rustdesk-5:
            enabled: true
            port: 21117 # Relay server
            protocol: "TCP"
          rustdesk-6:
            enabled: true
            port: 21119
            protocol: "TCP"
      server:
        controller: hbbs
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: "10.0.10.25"
          external-dns.alpha.kubernetes.io/hostname: rustdesk.${SECRET_DOMAIN}
        ports:
          rustdesk-1:
            enabled: true
            port: 21115
            protocol: "TCP"
          rustdesk-2:
            enabled: true
            port: 21116 # ID server
            protocol: "TCP"
          rustdesk-3:
            enabled: true
            port: 21116
            protocol: "UDP"
          rustdesk-4:
            enabled: true
            port: 21118
            protocol: "TCP"
    ingress:
      hbbr:
        enabled: true
        className: internal
        hosts:
          - host: &host remoterelay.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: relay
                  port: 21117
        tls:
          - hosts:
              - *host
      hbbs:
        enabled: true
        className: internal
        hosts:
          - host: &host remoteserver.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: server
                  port: 21116
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /db
