---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: Files
        group: Applications
        url: https://files.${SECRET_DOMAIN}/status.php
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover
            send-on-resolved: true
