---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rustdesk
  namespace: flux-system
spec:
  targetNamespace: default
  path: ./kubernetes/apps/default/rustdesk/app
  components:
    - ../../../components/volsync
    - ../../../components/gatus/guarded
  postBuild:
    substitute:
      APP: *app
      # VOLSYNC_CLAIM: portainer-pvc
      VOLSYNC_CAPACITY: 20Gi
      VOLSYNC_STORAGECLASS: openebs-hostpath
      # VOLSYNC_START_MINUTE: "11"
      # VOLSYNC_CACHE_CAPACITY: "1Gi"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m

