apiVersion: v1
kind: Secret
metadata:
  name: discord_webhook
  namespace: monitoring
type: Opaque
stringData:
  webhook-url: ENC[AES256_GCM,data:XqYL/cT7q43OA3w+on7yReFIqY461hHGYqcLQo4GxL1ydOfllXNxs7MrQguD/9rZK0uSbKOCMS6NEkNLa7vSgX54fi0cWVNBD1vCT6iankufEoPsVdG4F3nPRYNctPcG7DsFOPjj9h6guQT7iabZHbmFVLxHs1i35w==,iv:dZ2vmF75dVHTJb8KvWSKz/MCKWnyJQvIsc1MnUdFh5k=,tag:EDzblwonWI/lt/FG77wp4g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUb2hOV1FPNjlLbHlGWUM5
        ckluWVhma000MFNncmpmTisyMCtCVUtYSEFRCmFuVHMzV210cFhadWFxSXh3NFBq
        R0p1QjY0MXBpSHEwbjd5akN1emI2bW8KLS0tIFJ2SEpScloyTnB4djVQYW51U1Qy
        dlRzNDRWeEtrWFhlZkhCTXp3Rk4yMXcKAc3o4JgLelPsfVw+Xv/S6JzYemj0n9r2
        g1z4CcfHoH7S8vqWUDsc93marLn9FrWlIbvFNker7zMKztqKtiif1A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-03T16:06:54Z"
  mac: ENC[AES256_GCM,data:KpGrwvHzCrtywgUEyuAROBWALhWC6/nJkhmoa0fEe9DuCSDPI9HBJ+fhsGgtPYvQuRUgwkeTKthlVcT4yVdbAY0tYKd3fbf5IgI6MaH+zNhm08dApQwU5+3lLD6I0lMbyAc7rsB+b7Z6FtUCupvs2AR1ZIVqwMg9Hz/Hg44HBSs=,iv:qDBLmdbyugNuwrB3R/TWAvRrwiDXzxN/da40AAouVZ0=,tag:vkySefbfdgN/obb2V3Wj8A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
