apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook
  namespace: monitoring
type: Opaque
stringData:
  DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:Q+JPtLEIBqYjkT9qg67ykasuVY3tblk5XWjLjDwSIG7c2h6UHusAFsDdCLsdg19ET4REjbHN9QN6Bicxpx+hCyOYeclM3hv1Hz38Pg88clchbdtSoxRV4w9GhYU/8Npor80muL5eNSh/ytn7s484p0SwrrX9suDq5g==,iv:ccEaC42F3PImoYbrzVAnW2gWBkUfVMw9mcho8ZybaEQ=,tag:mUV3hmvd3To7ISuFy/d2HQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gvz08t4h6028wf02xlgfyj67ne4zsm9e2znpz47cnmlwg5ywvvwsxgxy3u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SmM3bFBEbm5GZ0h3U0pY
        NVlKSjNqbzBtZ1JsL0ZwcDBhNzZINlBzZGljCnVsRFlub0tqbWNXaURKdHpoK1hE
        UytlNzdKM2FmZWh5K0xvQnMwSXd3alUKLS0tIG4rTEFNZmZQV0kzeExoRDdKVzlS
        UDZnV1pVWHdyU0t2b2hPTEV6eUZQa0EKzelCHsiM7POSzyBSmrZ94LqBELQ06yt2
        GRHP6H72HZZbJlgPo8T3lKw0Qw8mb6FeBbO3OqCtRsBPBFffiuTYsw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-03T16:34:04Z"
  mac: ENC[AES256_GCM,data:0OknzeP8PVzfmPfJdAcSMhNterf7Q1npmj80lC6Pr/qIwRuM3Wf/8gxt0Kx+qAgF1eibvRtcPv8FhQl7likuR5WmUZ8sAz9jwpgjkA+rX/rnUZZWH1dTQdm8HDW5eLGTgAW5yphlzo6aTSVdpvwwSs2aw8Rf90+IWBfmPvOw3V0=,iv:bxg2rP8cYsAeKR/nKYNmTC9gBGU8Cq1si3WGe/4luEc=,tag:0/H83oEipGivEkY4PakWJw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
