---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gatus
  namespace: monitoring
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
  storageClassName: ceph-rbd
