---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hayani-xyz
spec:
  secretName: hayani-xyz-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: hayani.xyz
  dnsNames: ["hayani.xyz", "*.hayani.xyz"]
