---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
resources:
  - ./snapshot-controller/ks.yaml
  - ./csi-driver-nfs/ks.yaml
  - ./volsync/ks.yaml
  - ./minio/ks.yaml
  - ./openebs-system/openebs/ks.yaml
  - ./immich/ks.yaml
  # - ./nextcloud/ks.yaml
components:
  - ../../components/common
  # - ../../components/gatus/guarded
  # - ../../../shared/meta/components/alerts
  # - ../../../shared/meta/components/global-vars
  # - ../../../shared/meta/components/namespace
  # - ../../../shared/meta/components/sops
